### ISSUE TITLE
Electron: target should be required

### ISSUE THREAD

**Issue by dungahk** [nstudio/xplat#109]
The schematic fails if a target is not provided.

**Comment by NathanWalker** [comment]
@dungahk it should throw an exception if target is not provided no?
```
if (!options.target) {
    throw new SchematicsException(`Missing target argument. Provide the name of the web app in your workspace to use inside the electron app. ie, web-myapp`);
  }
```
https://github.com/nstudio/xplat/blob/master/src/app.electron/index.ts#L24-L26

**Comment by dungahk** [comment]
I'm sorry, my report was not very clear. What I mean is that it should be stated as a required option, because if you do not specify it, the schematics fail, as you mentioned there is a validation for that.

What I mean is that it should be stated as required here: https://github.com/nstudio/xplat/blob/master/src/app.electron/schema.json#L46

Because I normally use Angular Console and it shows the required fields before the optional ones. I'll try to get a screenshot of this later.

**Comment by NathanWalker** [comment]
x-prompt used now with v8
