### ISSUE TITLE
Question about creating & accessing shared components

### ISSUE THREAD

**Issue by zoitsa** [nstudio/xplat#11]
@NathanWalker I'm trying to learn the best approach for creating a shared component in libs and then accessing it either in xplat or my app. 

I am testing out a search feature that I previously built on the web and want to make it accessible on mobile and web. I added my ngrx and api.service to libs. I manually added the following component  `libs/features/ui/base/search.base-component.ts` to add in my search code.

I tried importing that into my web project's home component (just to test) and I get compiling errors and the following error: 
`ERROR Error: Uncaught (in promise): Error: Can't resolve all parameters for HomeComponent: (?).
Error: Can't resolve all parameters for HomeComponent: (?).`

Can you assist with the proper work-flow and any explanation?

**Comment by NathanWalker** [comment]
@zoitsa I enjoyed chatting with you on Slack today - I'll close this since we solved the issue but feel free to open another if something else comes up 👍
