### ISSUE TITLE
Bug: Generating pipe or directive

### ISSUE THREAD

**Issue by eng-ahmedsaleh** [nstudio/xplat#110]
I still have an issue while generating pipe or directive, this may be related to #68 but not resolved in my case.

example: generate pipe to the default feature (UI) 

`ng generate @nstudio/schematics:pipe size`

> CREATE libs/features/ui/pipes/size.pipe.ts (183 bytes)
> UPDATE libs/features/ui/pipes/index.ts (476 bytes)
> UPDATE libs/features/ui/ui.module.ts (362 bytes)

**libs/features/ui/pipes/index.js**    this exports a _PIPES_ array.
```
export const PIPES = [
  DateOrderPipe,
  SizePipe
];
```

**libs/features/ui/ui.module.ts**      imports and uses  _UI_PIPES_ array which is not found (not exported)
`import { UI_PIPES } from './pipes';`
`  exports: [...MODULES, ...PIPES, ...UI_PIPES]
`

> The same thing applied with directives

**Comment by NathanWalker** [comment]
Thanks for heads up - this is fixed in 7.4.4 now 👍 (if generated in workspace already can just update or remove the `...PIPES` one)...should be `UI_PIPES` in this case. 7.4.4 will make sure of that for new workspaces.
