### ISSUE TITLE
Is there a way to set it up in local mode to easily separate Angular versions?

### ISSUE THREAD

**Issue by dmitryr117** [nstudio/xplat#111]
Hi I noticed that in installation instructions xplat says that I should set up Angular in -g global mode. However there are some projects that might be using older angular version. Hence being able to separate them in different folders with different versions of Angular would be of big benefit. Is there a way to do it?

**Comment by dungahk** [comment]
You don't need to install the package globally, you can use npx.

`npx -p @angular/cli -p create-nx-workspace [your command here]`

**Comment by dmitryr117** [comment]
I think there is something incomplete in this command. I get this:
```
sudo npx -p @angular/cli -p create-nx-workspace testspace
[sudo] password for mainuser: 
npx: installed 348 in 20.996s
npx: command not found: testspace
```

**Comment by dmitryr117** [comment]
Ok. I finally got it to work with this command on my Ubuntu 18.04:
`sudo npx -p @nrwl/schematics -p @angular/cli create-nx-workspace [testspace]`

then change the permissions for folder, subfolders and subfiles:
`sudo chown -R username:username ./testspace`

then cd into /testspace or whatever project folder was made and do as usual
`npm install @nstudio/schematics --save-dev`

then every time we have to do ng command instead we do an npx ng command like this:
`ng g xplat --prefix=foo --platforms=web,nativescript,ionic,electron,nest`

That's all
