### ISSUE TITLE
Generate with a sample feature error

### ISSUE THREAD

**Issue by roarkredux** [nstudio/xplat#112]
Hello.  And thanks for your work.

This is my first time posting any issue on GitHub.  I hope I am following the protocol.

I am trying to follow the instructions given under the section "Generate with a sample feature".

I have done the following:

1. npm install -g @nrwl/schematics
2. npm install -g @angular/cli
3. create-nx-workspace xplatSample
4. cd xplatSample
5. npm install @nstudio/schematics --save-dev
6. ng g xplat --prefix=foo --sample

I get the following error:

"You must specify which platforms you wish to generate support for. For example: ng g xplat --prefix=foo --platforms=web,nativescript,ionic,electron,nest".

I experimented and received errors on these attempts:

ng g xplat --prefix=foo --platforms=sample

"sample is not a supported platform. Currently supported: web,nativescript,ionic,electron,nest"

ng g xplat --sample

"You must specify which platforms you wish to generate support for. For example: ng g xplat --prefix=foo --platforms=web,nativescript,ionic,electron,nest"

Thanks again for all you do.  You and your fellow pioneers bring much value to what the rest of us try to do.

**Comment by NathanWalker** [comment]
Hi @roarkredux and thanks for kind words.

You did all the steps right except the last one (6.) Instead run command like this:

```
ng g xplat --prefix=foo --sample --platforms=web
```

Or any number of platform combinations as the error message mentions, ie:

```
ng g xplat --prefix=foo --sample --platforms=web,nativescript,ionic,electron,nest
```
