### ISSUE TITLE
jest.config.js not found

### ISSUE THREAD

**Issue by nongrata081** [nstudio/xplat#113]
After:
- scaffolding nx workspace with `create-nx-workspace [your workspace name]`
- installing xplat schematics with `npm install @nstudio/schematics --save-dev`
- generating xplat architecture with `ng g xplat --prefix=foo --platforms=web`
- generating angular app with `ng g app name` with jest as a test-runner
- adding npm script for unit-testing to package-json `"test.web.name": "ng test web-name"`
- running unit tests with `npm run test.web.name` produces an error:

```
● Validation Error:

  Preset ../../jest.config.js not found.

  Configuration Documentation:
  https://facebook.github.io/jest/docs/configuration.html
```

[Sample repo](https://github.com/nongrata081/xplat-jest)

1) Googling lead me to this [nx issue](https://github.com/nrwl/nx/issues/739) which was resolved, however this error pops up again now. Paths in jest configs are correct. How can that be fixed?

2) Another thing is that on step of generating xplat architecture scaffolded are karma files in `testing` directory and karma configs are added to angular.json. Is that something we want to be scaffolded on that step? We have a possibility to choose test-runner (karma | jest) when generating an app, so shouldn't all test-related files/configs be scaffolded only on app generation step?

**Comment by NathanWalker** [comment]
Thanks @nongrata081 - Jest and Cypress were recently added as default choices by Nx (vs. the Karma/Protractor) and we need to verify a few things given these new defaults. You are correct that it should handle this as you expect 👍
