### ISSUE TITLE
Cannot generate angular app in custom directory

### ISSUE THREAD

**Issue by nongrata081** [nstudio/xplat#114]
After:
- scaffolding nx workspace with `create-nx-workspace [your workspace name]`
- installing xplat schematics with `npm install @nstudio/schematics --save-dev`
- generating xplat architecture with `ng g xplat --prefix=foo --platforms=web`
- generating angular app with `ng g app someapp --directory=custom` or inputting custom path via prompt, produces an error:

```
Path "/apps/web-someapp/src/index.html" does not exist.
```

[Sample repo](https://github.com/nongrata081/xplat-jest)

Found a similar [xplat issue 78](https://github.com/nstudio/xplat/issues/78) but in my case versions are @nstudio/schematics@7.4.8, @angular/cli@7.3.1 and there are no capital letters neither in app name nor in dirname. How can that be fixed?

It does work fine for generating a react / web components / ionic / nativescript / nest app though.

**Comment by NathanWalker** [comment]
@nongrata081 full `directory` support is not added at moment however definitely on a todo list.
