### ISSUE TITLE
Failing `ng test libs` & `ng test xplat` after `ng g xplat`

### ISSUE THREAD

**Issue by nongrata081** [nstudio/xplat#116]
After:

- scaffolding an empty nx workspace with `create-nx-workspace [your workspace name]`
- installing xplat schematics with `npm install @nstudio/schematics --save-dev`
- generating xplat architecture with `ng g xplat --prefix=foo --platforms=web`
- running `yarn`
- running `ng test libs` or `ng test xplat` fails, due to **missing devDependencies**: karma, karma-jasmine, karma-chrome-launcher, karma-jasmine-html-reporter, karma-coverage-istanbul-reporter, @types/jasmine

If those dependencies are present in package.json and if you install dependencies then tests pass.

1) After generating xplat architecture folders `libs` and `xplat` contain `.spec.ts` files, so on that step it would make sense to add missing devDependencies to the package json, so that right after scaffolding the xplat architecture one can install dependencies and run tests for scaffolded folders right away. As a developer I am used to verifying functionality of whatever I develop step by step, thus making it easier to localise at which step the error arises.

2) Now `ng g xplat ...` scaffolds the xplat architecture with karma by default. Does it make sense to switch to jest by default, following Nx? But then add proper set of dependencies to package.json after `ng g xplat` despite of which test runner was it scaffolded with?

**Comment by NathanWalker** [comment]
I think it’s best to stick with Nx defaults so since those are now Jest and Cypress we should probably change the architecture tests to use Jest by default as well. Thoughts?

**Comment by nongrata081** [comment]
Yes, it would be awesome
