### ISSUE TITLE
Packaging for 8.x

### ISSUE THREAD

**Issue by NathanWalker** [nstudio/xplat#118]
Due to upcoming changes with Nx packaging:
https://github.com/nrwl/nx/issues/1256

We will likely plan to follow similar pattern which will ultimately simplify the schematics as well as provide things to be split up even better to solve cases like [this](https://github.com/nstudio/xplat/issues/53) where app generators could be used outside of the architecture allowing users to work with or without the supporting architecture base depending on their needs.

Thinking along these lines to match the Nx direction with 8.x:

```
ng g @xplat/electron:app myapp
ng g @xplat/ionic:app myapp
ng g @xplat/nativescript:app myapp
// etc.
```

**Comment by sajidali** [comment]
@NathanWalker NX 8 has been released. waiting for updated xplat...

**Comment by NathanWalker** [comment]
Thanks @sajidali we're planning on this month. In meantime if you have specific items affected with Nx 8 please report here.

**Comment by barryajones** [comment]
@NathanWalker not sure if this is related but since upgrading to Angular 8 I can no longer generate a new web app https://github.com/nstudio/xplat/issues/127.

Although the github repo for the nx schematics is [version 8.1.0](https://github.com/nrwl/nx/blob/master/package.json#L3) this has not been deployed to the npm registry.

**Comment by sanyashvets** [comment]
> @NathanWalker not sure if this is related but since upgrading to Angular 8 I can no longer generate a new web app #127.
> 
> Although the github repo for the nx schematics is [version 8.1.0](https://github.com/nrwl/nx/blob/master/package.json#L3) this has not been deployed to the npm registry.

same

**Comment by csikosjanos** [comment]
I was about to start a new xplat project but it fails at the following step:
```npm install @nstudio/schematics --save-dev```

with the following error message:
```
...
An issue were detected during patching the nx-formatter [Error: ENOENT: no such file or directory, open './node_modules/@nrwl/schematics/src/command-line/format.js']
...
```

It seams in the new Nx the `@nrwl/schematics` has been split up and the `command-line` is now in the `@nwrl/workspace` package.

Thanks!

**Comment by gperdomor** [comment]
@NathanWalker any progress?

**Comment by NathanWalker** [comment]
We're anxious to get the updates out but are taking bit more time to ensure the structure meets the goals a lot of us have wanted with some broader use cases. We'll close this as soon as we have the updates out and hopeful won't be longer than 2 weeks. Possible that for those experiencing any purely install related issues (aside from generators) may could roll initial update out sooner to clear that.
