### ISSUE TITLE
ng build --prod failing with Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule' 'NgModule' calls 'ɵmakeDecorator'.

### ISSUE THREAD

**Issue by davidberardozzi** [nstudio/xplat#119]
After :

- scaffolding an empty nx workspace with `create-nx-workspace [your workspace name]`
- installing xplat schematics with `npm install @nstudio/schematics --save-dev`
- generating xplat architecture with `ng g xplat --prefix=foo --platforms=web, ionic`
- creating an ionic app with `ng g app.ionic myapp`

Running `ng build --prod` in the newly generated `myapp` root folder gives:

```
ERROR in ../../../xplat/ionic/core/core.module.ts(7,2): Error during template compile of 'fooIonicCoreModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.
```

Where could I investigate? (already been through https://github.com/angular/angular/issues/23609 without finding anything useful)
Thanks for your great work.

**Comment by davidberardozzi** [comment]
For information, using `ng build --prod --aot=false --build-optimizer=false` allows to buld the project with the prod flag.

**Comment by pinalmdave** [comment]
I was also receiving same error and I was able to do prod build using : ng build --prod --aot=false --build-optimizer=false. So good for the time being, but for prod, eventually I want AOT build with optimizer. So this is just a temporary solution.

**Comment by enzonotario** [comment]
Hi folk! Do you found a solution? My builds are so slow without AOT :( Thanks in advance!

**Comment by davidberardozzi** [comment]
Not yet, I was trying to check every error involving the use of forRoot but not yet succeeded. I have already been trying to use all suggested combinations of angularCompilerOptions without success (as seen in main angular issue [here](https://github.com/angular/angular/issues/23609#issuecomment-386876693) ).

**Comment by NathanWalker** [comment]
This should be fixed with v8 of xplat. See the new [Getting Started Guide](https://nstudio.io/xplat/getting-started/getting-started). The new Ionic app generators use latest 4.7 Nitrogen release. You can now also generate Stencil Ionic apps when you choose not to use frontend framework when prompted now.
