### ISSUE TITLE
generating angular app with --sample fails

### ISSUE THREAD

**Issue by jaunkst** [nstudio/xplat#125]
Fails before prompted to use routing option.
Nothing is generated at this point so it fails early

ng g @nstudio/schematics:app bar --sample
Path "/apps/web-bar/src/app/features/home/components/home.component.html" does not exist.

**Comment by NathanWalker** [comment]
Thank you for the report @jaunkst 
There’s been some underlying changes with Nx recently and will need to check the sample flag.

**Comment by jaunkst** [comment]
One more schemstic template issue I found is the electron app generator is defaulting to Jasmine when using jest.

I tried everything but inoic. Otherwise It all seems to work for me

**Comment by NathanWalker** [comment]
With the upcoming v8 changes we'll be removing the `sample` flag since sample repo's will be a better source of understanding as well as helping to simplify the schematics as whole 👍
