### ISSUE TITLE
livereload ionic android

### ISSUE THREAD

**Issue by sanyashvets** [nstudio/xplat#129]
is it possible to put livereload to android/ios devices?
Like a standard ionic command: `ionic cordova run android -l`

Also, freshly generated app is not running with NG 8 (missing @capacitor/core and in global.scss - `@import '@monorepo/ionic/...'` that `ionic` folder does not exist

**Comment by NathanWalker** [comment]
Fixed in v8 - livereload should work as long as Ionic supports it.
