### ISSUE TITLE
Ionic - InjectionToken @ngrx/store Feature Reducers -> Injector

### ISSUE THREAD

**Issue by Brandejs** [nstudio/xplat#130]
Hi,

it is possible to use NgModule from _libs_ that imports **StoreModule.forFeature(...)** in ionic apps? 

I'm getting an error 
```
NullInjectorError: StaticInjectorError(AppModule)[InjectionToken @ngrx/store Feature Reducers -> Injector]: 
  StaticInjectorError(Platform: core)[InjectionToken @ngrx/store Feature Reducers -> Injector]: 
    NullInjectorError: No provider for Injector!
```

I assume that the error is due to another node_modules folder inside ionic-app.

**Comment by NathanWalker** [comment]
Hi @Brandejs that is possible yeah. For example in libs you can have something like this:
```
import { NgModule } from '@angular/core';
import { StoreModule } from '@ngrx/store';
import { userSettingsReducer } from './state/user-settings.reducer';
import { EffectsModule } from '@ngrx/effects';
import { UserSettingsEffects } from './state/user-settings.effect';

@NgModule({
  imports: [StoreModule.forFeature('userSettings', userSettingsReducer), EffectsModule.forFeature([UserSettingsEffects])],
  providers: [UserSettingsEffects]
})
export class UserSettingsModule {

}

```
Then just import that module into any of your Ionic modules. (lazy or not).

**Comment by Brandejs** [comment]
Hi @NathanWalker. Thanks for your reply. 

Thats exactly what i', doing. I have simple Module in _libs/_

```
import { NgModule } from '@angular/core';
import { StoreModule } from '@ngrx/store';
import { reducer } from './reducer';

@NgModule({
  imports: [StoreModule.forFeature('authState', reducer)],
})
export class AuthModule {}

```

When I import that module into _apps/web-_ or _xplat/web_. Everything is working. 

```
@NgModule({
  imports: [
    StoreModule.forRoot(reducers, {
      ....
    }),
    AuthModule // OK
  ]
})
export class WebCoreModule {
}
```


But when I import that into _apps/ionic-_ or _xplat/ionic_. Im getting this error. 

```
@NgModule({
  imports: [
    StoreModule.forRoot(reducers, {
      ....
    }),
    AuthModule // ERROR
  ]
})
export class IonicCoreModule {
}
```

```
NullInjectorError: StaticInjectorError(AppModule)[InjectionToken @ngrx/store Feature Reducers -> Injector]: 
  StaticInjectorError(Platform: core)[InjectionToken @ngrx/store Feature Reducers -> Injector]: 
    NullInjectorError: No provider for Injector!
```

**Comment by NathanWalker** [comment]
@Brandejs please post your Ionic `package.json` contents here along with the workspace root `package.json` - I'd like to check something.

**Comment by Brandejs** [comment]
Root package.json 
`{
  "name": "loow",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "nx lint && ng lint",
    "e2e": "ng e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "update": "ng update @nrwl/workspace",
    "update:check": "ng update",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "clean.shared": "cd libs/ && git clean -dfX && cd ../xplat/ && git clean -dfX",
    "clean": "npx rimraf -- hooks node_modules package-lock.json && yarn install",
    "start.nativescript.loow.ios": "cd apps/nativescript-loow && tns run ios --emulator --bundle",
    "debug.nativescript.loow.ios": "cd apps/nativescript-loow && tns debug ios --emulator --bundle",
    "start.nativescript.loow.android": "cd apps/nativescript-loow && tns run android --emulator --bundle",
    "start.nativescript.loow.preview": "cd apps/nativescript-loow && tns preview --bundle",
    "clean.nativescript.loow": "cd apps/nativescript-loow && npx rimraf -- hooks node_modules platforms package-lock.json && yarn install && npx rimraf -- package-lock.json",
    "start.web.loow": "ng serve web-loow",
    "build.ionic.loow": "cd apps/ionic-loow && yarn run build:web",
    "prepare.ionic.loow": "yarn run clean && yarn run clean.ionic.loow && yarn run build.ionic.loow",
    "prepare.ionic.loow.ios": "yarn run prepare.ionic.loow && cd apps/ionic-loow && yarn run cap.add.ios",
    "prepare.ionic.loow.android": "yarn run prepare.ionic.loow && cd apps/ionic-loow && yarn run cap.add.android",
    "open.ionic.loow.ios": "cd apps/ionic-loow && yarn run cap.ios",
    "open.ionic.loow.android": "cd apps/ionic-loow && yarn run cap.android",
    "sync.ionic.loow": "cd apps/ionic-loow && yarn run cap.copy",
    "start.ionic.loow": "cd apps/ionic-loow && yarn start",
    "clean.ionic.loow": "cd apps/ionic-loow && npx rimraf -- hooks node_modules platforms www plugins ios android package-lock.json && yarn install && rimraf -- package-lock.json"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "8.1.0",
    "@angular/common": "8.1.0",
    "@angular/compiler": "8.1.0",
    "@angular/core": "8.1.0",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "8.1.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.1.0",
    "@angular/platform-browser-dynamic": "8.1.0",
    "@angular/router": "8.1.0",
    "@ionic-native/core": "^5.9.0",
    "@ionic-native/splash-screen": "^5.9.0",
    "@ionic-native/status-bar": "^5.9.0",
    "@ionic/angular": "^4.6.0",
    "@loow/scss": "file:libs/scss",
    "@loow/web": "file:xplat/web",
    "@ngrx/effects": "8.0.1",
    "@ngrx/entity": "8.0.1",
    "@ngrx/router-store": "8.0.1",
    "@ngrx/schematics": "8.0.1",
    "@ngrx/store": "8.0.1",
    "@ngx-translate/core": "~11.0.0",
    "@ngx-translate/http-loader": "~4.0.0",
    "@nrwl/angular": "8.2.0",
    "@nrwl/nx": "^7.8.7",
    "bootstrap-scss": "^4.3.1",
    "core-js": "^2.5.4",
    "firebase": "^6.2.4",
    "firebase-admin": "^8.2.0",
    "firebase-functions": "^3.0.2",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "5.4.3",
    "tns-core-modules-widgets": "6.0.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.0",
    "@angular/cli": "8.1.0",
    "@angular/compiler-cli": "^8.1.0",
    "@angular/language-service": "^8.1.0",
    "@ionic/angular-toolkit": "2.0.0",
    "@ngrx/store-devtools": "8.0.1",
    "@nrwl/cypress": "8.0.0",
    "@nrwl/jest": "8.0.0",
    "@nrwl/schematics": "^8.1.0",
    "@nrwl/workspace": "8.0.0",
    "@nstudio/schematics": "^7.4.8",
    "@types/jest": "24.0.9",
    "@types/jquery": "3.3.6",
    "@types/node": "~8.9.4",
    "@types/jasmine": "^3.3.13",
    "@types/jasminewd2": "^2.0.6",
    "jasmine-core": "^3.4.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "codelyzer": "^5.0.1",
    "cypress": "3.1.0",
    "dotenv": "6.2.0",
    "jest": "24.1.0",
    "jest-preset-angular": "7.0.0",
    "node-sass": "^4.12.0",
    "prettier": "1.16.4",
    "tns-platform-declarations": "~5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "protractor": "^5.4.2",
    "typescript": "~3.4.5"
  },
  "xplat": {
    "prefix": "loow"
  }
}
`


Ionic - package.json

`{
"name": "ionicloow",
"license": "SEE LICENSE IN <your-license-filename>",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ionic serve",
    "build:web": "ng build",
    "build:ionic": "ng build && npm run cap.copy",
    "build:mobile": "npm run cap.copy && npm run cap.update",
    "build:mobile:ios": "npm run cap.copy && npx cap update ios",
    "build:mobile:android": "npm run cap.copy && npx cap update android",
    "build:prod": "npm run build:web -- --prod && npm run build:mobile",
    "cap.add.ios": "npx cap add ios",
    "cap.add.android": "npx cap add android",
    "cap.ios": "npx cap open ios",
    "cap.android": "npx cap open android",
    "cap.copy": "npx cap copy",
    "cap.update": "npx cap update",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "dependencies": {
    "@angular/animations": "file:../../node_modules/@angular/animations",
    "@angular/common": "file:../../node_modules/@angular/common",
    "@angular/core": "file:../../node_modules/@angular/core",
    "@angular/forms": "file:../../node_modules/@angular/forms",
    "@angular/platform-browser": "file:../../node_modules/@angular/platform-browser",
    "@angular/platform-browser-dynamic": "file:../../node_modules/@angular/platform-browser-dynamic",
    "@angular/router": "file:../../node_modules/@angular/router",
    "@angular/fire": "file:../../node_modules/@angular/fire",
    "@capacitor/android": "^1.0.0-beta.17",
    "@capacitor/cli": "^1.0.0-beta.17",
    "@capacitor/core": "^1.0.0-beta.17",
    "@capacitor/ios": "^1.0.0-beta.17",
    "@loow/ionic": "file:../../xplat/ionic",
    "@loow/scss": "file:../../libs/scss",
    "@loow/web": "file:../../xplat/web",
    "@ionic-native/core": "file:../../node_modules/@ionic-native/core",
    "@ionic-native/splash-screen": "file:../../node_modules/@ionic-native/splash-screen",
    "@ionic-native/status-bar": "file:../../node_modules/@ionic-native/status-bar",
    "@ionic/angular": "file:../../node_modules/@ionic/angular",
    "@ngrx/effects": "file:../../node_modules/@ngrx/effects",
    "@ngrx/router-store": "file:../../node_modules/@ngrx/router-store",
    "@ngrx/store": "file:../../node_modules/@ngrx/store",
    "@ngx-translate/core": "file:../../node_modules/@ngx-translate/core",
    "@ngx-translate/http-loader": "file:../../node_modules/@ngx-translate/http-loader",
    "@nrwl/nx": "file:../../node_modules/@nrwl/nx",
    "rxjs": "file:../../node_modules/rxjs",
    "zone.js": "file:../../node_modules/zone.js"
  },
  "devDependencies": {
    "@angular-devkit/architect": "file:../../node_modules/@angular-devkit/architect",
    "@angular-devkit/build-angular": "file:../../node_modules/@angular-devkit/build-angular",
    "@angular-devkit/core": "file:../../node_modules/@angular-devkit/core",
    "@angular-devkit/schematics": "file:../../node_modules/@angular-devkit/schematics",
    "@angular/cli": "file:../../node_modules/@angular/cli",
    "@angular/compiler": "file:../../node_modules/@angular/compiler",
    "@angular/compiler-cli": "file:../../node_modules/@angular/compiler-cli",
    "@angular/language-service": "file:../../node_modules/@angular/language-service",
    "@ionic/angular-toolkit": "file:../../node_modules/@ionic/angular-toolkit",
    "@types/jasmine": "file:../../node_modules/@types/jasmine",
    "@types/jasminewd2": "file:../../node_modules/@types/jasminewd2",
    "@types/node": "file:../../node_modules/@types/node",
    "codelyzer": "file:../../node_modules/codelyzer",
    "jasmine-core": "file:../../node_modules/jasmine-core",
    "jasmine-spec-reporter": "file:../../node_modules/jasmine-spec-reporter",
    "karma": "file:../../node_modules/karma",
    "karma-chrome-launcher": "file:../../node_modules/karma-chrome-launcher",
    "karma-coverage-istanbul-reporter": "file:../../node_modules/karma-coverage-istanbul-reporter",
    "karma-jasmine": "file:../../node_modules/karma-jasmine",
    "karma-jasmine-html-reporter": "file:../../node_modules/karma-jasmine-html-reporter",
    "protractor": "file:../../node_modules/protractor",
    "ts-node": "file:../../node_modules/ts-node",
    "tslint": "file:../../node_modules/tslint",
    "typescript": "file:../../node_modules/typescript"
  }
}
`

**Comment by Brandejs** [comment]
Well. I created a new project from scratch and it start to work, I copied modules from the first one and everything is OK. I just don't know why.

**Comment by NathanWalker** [comment]
@Brandejs Interesting. Yeah it's likely some dependency was mismatched somewhere leading to an error like that. Glad you got it going now 👍
