### ISSUE TITLE
Add support for node 12

### ISSUE THREAD

**Issue by ph55** [nstudio/xplat#134]
When creating new project it fails with multiple errors related to node 12 support in different packages.

SASS:
`
../src/create_string.cpp:17:25: error: no matching constructor for initialization of 'v8::String::Utf8Value'
`

Fix - [@angular/cli@7.3.9 and @angular-devkit/build-angular@0.13.9](https://github.com/angular/angular-cli/issues/14339#issuecomment-490215337)

There was also error when electron was added. Related to [fs-xattr](https://github.com/LinusU/fs-xattr/issues/27) / [appdmg](https://github.com/LinusU/node-appdmg/issues/181)

**Comment by NathanWalker** [comment]
Thank you @ph55 the refactor should solve this yep as it's using latest cli and devkit 👍 thx for reminder to doublecheck. Adding as ref in the pr.
