### ISSUE TITLE
How do I generate a NestJs app in version 8?

### ISSUE THREAD

**Issue by barryajones** [nstudio/xplat#137]
The previous version of schematics allowed me to create a NestJs application. 

```
ng g app.nest nam
```

I can't see how to do this with version 8 of the schematics.

**Comment by NathanWalker** [comment]
@barryajones hi - Nx added Nest directly so you can now use Nrwl's directly now: 
```
nx g @nrwl/nest:app
```

You can view all the api options here:
https://nx.dev/angular/api/nest/schematics/application

**Comment by NathanWalker** [comment]
In `8.0.2` we'll look at allowing `nx g app` to pull up prompts including not only just xplat app generators but also include the full list of those from Nx itself directly as a convenience 👍

**Comment by barryajones** [comment]
The `nx g ...` command didn't work even though I have @nrwl/cli installed globally. I was getting:

```
 NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.
```

I was able to generate the nest app by using:

```
ng g @nrwl/nest:application
```

I was actually expecting a new folder under `./xplat` for **nest** to be created? Like there is for **electron** and **web**. I observed in my **tsconfig.json** before I added the nest app that there are paths specified for this:

```
paths: [
      ...
      "@app-name/nest": [
        "xplat/nest/index.ts"
      ],
      "@app-name/nest/*": [
        "xplat/nest/*"
      ],
]
```

Is this not the case anymore?

**Comment by NathanWalker** [comment]
Correct yeah Nest is all in Nx fully now. There still remains the possibility to have an xplat layer for Nest and would love to hear what you may have found useful to have in a platform layer for Nest?

Previously it was still to be determined what may end being a useful structure as a baseline to help large Nest development approaches.

If there is a structure you had found useful to help your Nest development then we could work something in for that.

**Comment by barryajones** [comment]
Thanks @NathanWalker. This is actually my first Nest app that I'm creating so I don't have any best practices to share right now.

**Comment by NathanWalker** [comment]
Awesome @barryajones Nest is fantastic have fun with it and if patterns emerge that you find useful share back and could create a nice layer to enhance Nest in Nx via xplat 👍
