### ISSUE TITLE
Cannot create new nx/xplat workspace

### ISSUE THREAD

**Issue by barryajones** [nstudio/xplat#139]
I'm trying to create a new nx/xplat workspace using

```
npx create-xplat-workspace myworkspace
```

A workspace is created but when it comes to installing the xplat tooling it's failing. I've tried this on 2 separate Macs. Below is the end of the output that shows the error.

```
>  NX   NOTE  Because you selected an Angular-specific preset, we generated an Nx workspace powered by the Angular CLI.

  Run 'create-nx-workspace --help' to see how to select a different CLI.

npm install -D @nstudio/xplat

> @nstudio/xplat@8.0.3 postinstall /Users/barryjones/Development/myworkspace/node_modules/@nstudio/xplat
> node src/utils/postinstall.js

Patch for nx format have been applied

>  XPLAT  Note:

  xplat is updating "/Users/barryjones/Development/myworkspace/.prettierignore" with a few important extra rules. You may double-check the contents afterwards to ensure they meet your satisfaction.

npm WARN @angular-eslint/builder@0.0.1-alpha.16 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-browser-dynamic@8.2.0 requires a peer of @angular/compiler@8.2.0 but none is installed. You must install peer dependencies yourself.

+ @nstudio/xplat@8.0.3
added 32 packages from 74 contributors in 12.172s
npx nx g @nstudio/xplat:init

>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.

? Would you like to generate xplat supporting architecture now? You can also generate later with: nx generate @nstudio/xplat:init web               [generate xplat Web support]
? Do you prefer to use a frontend framework? angular          [ensure platforms are added with Angular]
? Please input a 2-3 character prefix to use with xplat generators: ci

You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
Command failed: npx nx g @nstudio/xplat:init
```

**You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
Command failed: npx nx g @nstudio/xplat:init**

**Comment by barryajones** [comment]
I was able to resolve this by choosing empty nx workspace as the answer, rather than choosing the angular-nest option.
```
? What to create in the new workspace empty             [an empty workspace]
```

**Comment by NathanWalker** [comment]
Thanks for reporting this - seems like a schematics version mismatch which could lead to that - possible difference in @angular-devkit/schematics but I'm investigating.

**Comment by NathanWalker** [comment]
@barryajones  interesting so using `nx` does not work in this context - still looking at why and whether an issue with `nx` command line or expected.

The step in `create-xplat-workspace` which does this:
```
npx nx g @nstudio/xplat:init
```
Is what is causing it. The same command done using angular cli's `ng` works as expected:
```
ng g @nstudio/xplat:init
```

**Comment by NathanWalker** [comment]
Closing this in favor of https://github.com/nstudio/xplat/issues/140 which mentions same and this root issue will be solved when that one is closed, thanks again for reporting this.
