### ISSUE TITLE
nx generate app fails

### ISSUE THREAD

**Issue by ph55** [nstudio/xplat#140]
```
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

![image](https://user-images.githubusercontent.com/1386622/62414830-79822f00-b629-11e9-9b32-21eac61bec80.png)

Same error here - https://github.com/nstudio/xplat/issues/139

**Comment by NathanWalker** [comment]
Thanks for reporting this - seems like a schematics version mismatch which could lead to that - possible difference in @angular-devkit/schematics but I'm investigating.

**Comment by NathanWalker** [comment]
@ph55 Hmm interesting so using `nx` does not work in this context - still looking at why. But this works with the same above:

```
ng g app
```
With exact same options will work fine.

**Comment by ph55** [comment]
@NathanWalker ye figured out and working with this, thanks.

But it only works if you do both:
`npm install --save-dev @nstudio/xplat`
`ng add @nstudio/xplat` (select web)

---

If only `npm install --save-dev @nstudio/xplat` without `ng add`, following error thrown:
![image](https://user-images.githubusercontent.com/1386622/62416830-8f541c00-b64a-11e9-8114-d5506055b53f.png)

If you do `ng add @nstudio/xplat` but not selecting web, following error thrown:
![image](https://user-images.githubusercontent.com/1386622/62416846-f1148600-b64a-11e9-8f4f-f3793711ad43.png)

**Comment by ph55** [comment]
@NathanWalker also, not sure why doc says `npm install -dev @nstudio/xplat`. Typo ?
There is no such flag `-dev`.
If you run it it installs the package in regular dependencies.
```
-D, --save-dev: Package will appear in your devDependencies
```

**Comment by NathanWalker** [comment]
@ph55 thanks for heads up on docs you're correct that is definitely a typo. Will upload new docs after awhile with that clarified.

Your other comment about missing `web-angular` will be fixed in a moment as well. Thanks for all that you're reporting, very helpful. Depending on the order of commands it may miss installing the peer dependencies which that was related to; fixing that as well.

**Comment by NathanWalker** [comment]
@ph55 when you get a chance try one thing for me:

* rename `angular.json` to `workspace.json`

Don't need to change anything else, just that. And then try `nx g app` and lemme know if magically works. If so this may be something with `nx` commandline which I'll report to Nx or talk with them about it.

**Comment by ph55** [comment]
Sure. After renaming:

```
/bin/sh: yarn: command not found
Package install failed, see above.
```

![image](https://user-images.githubusercontent.com/1386622/62418612-f0451980-b675-11e9-9ba9-a3983f4dbdad.png)

**Comment by NathanWalker** [comment]
@ph55 nice thanks.  The docs are now updated to reflect `npm install --save-dev @nstudio/xplat` here:
https://nstudio.io/xplat/getting-started/getting-started

Talking with Nrwl about the nx vs. ng difference to find what's causing the original description here.

**Comment by cbetrifork** [comment]
The docs now says `npm install -save-dev @nstudio/xplat`.

It should be `npm install --save-dev @nstudio/xplat`

**Comment by Domvel** [comment]
Does not work. I tried your solution. `npm i -D @nstudio/xplat`. This does not work in my case. Select `ionic` `angular`. Fails on nx g app.

```bash
nx generate app

>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.

? What name would you like for this app? app1
? What type of app would like to create? ionic           [Ionic app]
You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

https://github.com/nstudio/xplat/issues/148
