### ISSUE TITLE
Electron app .gitignore improvement

### ISSUE THREAD

**Issue by ph55** [nstudio/xplat#142]
Hi, it's me again.

After starting electron app `start.electron.poker` two files will be generated:
`apps/electron-app/src/index.js`, `apps/electron-app/src/index.js.map`

Wouldn't it be nice to have it ignored on app generation ?
```
# NativeScript Template
*.js.map
*.js
```

Thanks for great tool.

**Comment by NathanWalker** [comment]
@ph55 good idea - published in `8.0.5` now 👍
