### ISSUE TITLE
Remove npm script prepare.ionic.traveler

### ISSUE THREAD

**Issue by chrene** [nstudio/xplat#145]
Hi,

I have recently added ionic to my xplat workspace. To start with I decided to try out adding iOS and get it going. After I got the iOS app to work I decided to try out adding Android to the ionic platform app. But running `prepare.ionic.traveler.android` wiped my iOS platform and then added the android platform. Having a look into the script, I could see why. It completely wipes everything and then adds the platform of your choice.

What I'm trying to ask is what the prepare scripts are actually good for after running it the first time? 
Is it in general a good idea to keep them in the package.json or should we remove them after doing the initial prepare? 

```
"clean.ionic.traveler": "cd apps/ionic-traveler && npx rimraf -- hooks node_modules platforms www plugins ios android package-lock.json && npm i && rimraf -- package-lock.json",
    
"prepare.ionic.traveler": "npm run clean && npm run clean.ionic.traveler && npm run build.ionic.traveler",

"prepare.ionic.traveler.android": "npm run prepare.ionic.traveler && cd apps/ionic-traveler && npm run cap.add.android",
```

**Comment by NathanWalker** [comment]
Good question - they provide a good reset point to either iOS or Android. It’s helpful sometimes to just clean everything and do a fresh run which is what those are good for outside of initial setup.

You can use them or remove them or tweak them for your own purposes.

**Comment by chrene** [comment]
@NathanWalker thanks for the quick response. I'll let them be there for now :)
