### ISSUE TITLE
workspace.json problems

### ISSUE THREAD

**Issue by Brandejs** [nstudio/xplat#146]
Hi, 

BUG 1:
In the latest version 8 if a new Ionic app is created. Cannot start live reload due to missing angular.json file in app directory(apps/ionic-myapp). It must be created manually with separate configuration.

```
$ cd apps/ionic-myapp && ionic capacitor run ios --livereload --address=0.0.0.0
> ng run app:serve --host=0.0.0.0 --port=8100
[ng] The run command requires to be run in an Angular project, but a project definition could not be found.
```
Question 1: 
Also i would like to know what is purpose of renaming angular.json to workspace.json? _Angular console_ and commands like _ng xi18n_ stoped working because of that. 

```
ng xi18n
The xi18n command requires to be run in an Angular project, but a project definition could not be found.
```
Question 2 / Bug2: 
If i rename workspace.json to angular.json, Angular console and commands start to work, but im getting error with xi18n

`ERROR in Unexpected value 'McbIonicCoreModule in .../myapp/xplat/ionic/core/core.module.ts' imported by the module 'CoreModule in .../myapp//apps/ionic-myapp/src/app/core/core.module.ts'. Please add a @NgModule annotation.`

**Comment by Brandejs** [comment]
Hi, yes i tried both NX and NG. with NX there is just info that it will forwad to angular CLI.
>  NX   NOTE  Nx didn't recognize the command, forwarding on to the Angular CLI.

I noticed that problem is not related just to xi18n, but it is also impossible to run build command with --prod flag. 

Im trying that on new project. Step to reproduce:
```
$ npx create-xplat-workspace myworkspace
> Angular CLI // this generate angular.json instead of workspace.json
> ionic
> angular
--- ERROR: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable. Command failed: npx nx g @nstudio/xplat:init
$ ng g @nstudio/xplat:init // With ng it works
> ionic
> angular
$ ng g app // nx g app - didn't work
> ionic
> angular
> Use xplat supp... : Y
$ yarn run prepare.ionic.APP_NAME
$ nx build ionic-APP_NAME // OK
$ nx build ionic-APP_NAME --prod // same error as with xi18n
```

```
$ ng version
Angular CLI: 8.0.1
Node: 12.4.0
OS: darwin x64
$ npx  --version
10.2.0

```

**Comment by Brandejs** [comment]
@NathanWalker  I'm glad my information is useful. I hope there will soon be a solution. :)

**Comment by Brandejs** [comment]
Hi @NathanWalker , is there any progress? I am going back to the Ionic application development. And I'm still getting into the same problem. Could you please describe how to start a new project with Ionic application and run build with --prod flag.

**Comment by Jason-Schroeder** [comment]
Hi @Brandejs and @NathanWalker . I came across a similar issue as described here and found the solution in a closed [issue](https://github.com/nstudio/xplat/issues/149). My issue was specifically related to running ionic production builds.

I had previously renamed the workspace.json file to angular.json in order to run ionic commands if required so i duplicated the file back into workspace.json (I now have both workspace.json and angular.json files in the ionic directory with the same contents to allow nx and ionic commands to run).

**My solution:**

Update the ionic app package.json file to only import dependencies that have not been included as a dependency in the root package.json file

run (within the ionic app directory)
```
npx rimraf -- hooks node_modules package-lock.json && npm i
```
then (from the root level)
```
nx build ionic-app --prod
```

I suspect the issue was being caused by duplicate packages being added during the build process if they are specified at the root and at the app level (even if the app level package.json file includes them using file:// url's). Maybe this could be documented? I will see if I can submit a PR with the README change if you can confirm that this is in fact the issue.

**Comment by Brandejs** [comment]
Hi, I found yesterday the same solution :) I had to remove all dependencies included in app-level project.json. Then prod build starts to work fine. It would be fine to document this. Or improve app generator to ignore dependencies when creating a new app.

**Comment by Jason-Schroeder** [comment]
I also just noticed that all @capacitor dependencies are required at the app level as well as any cordova plugins. If I don't add the capacitor dependencies to the app level package.json file I get the following error in android studio when building. I have not tested in XCode yet.

```
Unable to find a matching configuration of project :capacitor-android: None of the consumable configurations have attributes.
```

My ionic app package.json dependencies currently:
```
"dependencies": {
    "@capacitor/android": "file:../../node_modules/@capacitor/android",
    "@capacitor/core": "file:../../node_modules/@capacitor/core",
    "@capacitor/ios": "file:../../node_modules/@capacitor/ios",
    "cordova-sqlite-storage": "^3.4.0"
  }
```

@Brandejs I think the generator uses the ionic/capacitor cli internally to generate the new app so it might be difficult to ignore the dependencies.

**Comment by Brandejs** [comment]
I don't think that it uses ionic CLI. Otherwise, it would generate dependencies from "file:../".

Yeah, Capacitor and Cordova plugin must be included. with @capacitor/ios and @capacitor/android, I have a problem installing from file due to missing package.json. So I keep that in app-level package.json as well. (But that can be maybe due to that I'm still using beta version). I also keep @ionic-native/*. Did you test these? 

my apps/myapp-ionic/package.json

```
{
  "name": "myapp",
  "license": "SEE LICENSE IN <your-license-filename>",
  "version": "0.0.0",
  "scripts": {
    "cap.add.ios": "npx cap add ios",
    "cap.add.android": "npx cap add android",
    "cap.ios": "npx cap open ios",
    "cap.android": "npx cap open android",
    "cap.copy": "npx cap copy",
    "cap.update": "npx cap update"
  },
  "dependencies": {
    "@capacitor/android": "^1.0.0-beta.17",
    "@capacitor/core": "file:../../node_modules/@capacitor/core",
    "@capacitor/ios": "^1.0.0-beta.17",
    "@ionic-native/camera": "file:../../node_modules/@ionic-native/camera",
    "@ionic-native/core": "file:../../node_modules/@ionic-native/core",
    "@ionic-native/splash-screen": "file:../../node_modules/@ionic-native/splash-screen",
    "@ionic-native/status-bar": "file:../../node_modules/@ionic-native/status-bar",
    "@ionic/lab": "file:../../node_modules/@ionic/lab",
    "@ionic/pwa-elements": "file:../../node_modules/@ionic/pwa-elements",
    "@myapp/scss": "file:../../libs/scss"
  },
  "devDependencies": {
    "@capacitor/cli": "1.1.1",
    "@ionic/angular-toolkit": "file:../../node_modules/@ionic/angular-toolkit",
    "cordova-plugin-device": "file:../../node_modules/cordova-plugin-device",
    "cordova-plugin-ionic-keyboard": "file:../../node_modules/cordova-plugin-ionic-keyboard",
    "cordova-plugin-ionic-webview": "file:../../node_modules/cordova-plugin-ionic-webview",
    "cordova-plugin-splashscreen": "file:../../node_modules/cordova-plugin-splashscreen",
    "cordova-plugin-statusbar": "file:../../node_modules/cordova-plugin-statusbar",
    "cordova-plugin-whitelist": "file:../../node_modules/cordova-plugin-whitelist",
    "ionicons": "file:../../node_modules/ionicons"
  },
  "cordova": {
    "plugins": {
      "cordova-plugin-whitelist": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {},
      "com.telerik.plugins.nativepagetransitions": {},
      "cordova-plugin-camera": {},
      "cordova-wheel-selector-plugin": {}
    },
    "platforms": [
      "ios"
    ]
  }
}

```

**Comment by Jason-Schroeder** [comment]
Currently my @ionic-native/* packages are at the root-level and are not included in the app-level package.json file. They seem to be working fine with this configuration.

**Comment by Brandejs** [comment]
Hi @Jason-Schroeder, one last question. Did you somehow manage to run ionic with -livereload?

**Comment by Jason-Schroeder** [comment]
Hi @Brandejs. This is what I did to enable livereload. I have **not** tested this on iOS.

At the root package.json I added the following scripts:

```
"ionic.app.android.live": "cd apps/ionic-app && ionic capacitor run android --livereload --address=0.0.0.0",
"ionic.app.ios.live": "cd apps/ionic-app && ionic capacitor run ios --livereload --address=0.0.0.0"
```

To run on android with livereload:
```
npm run ionic.app.android.live
```
It will prompt you to select an interface (Ethernet, Wi-Fi, etc). Ensure both devices are connected to the same network.

This will open Android Studio where you can build the app normally. On app launch it should show a toast notification that says 
```
Using app server http://192.168.1.1:8100 
```
or something similar

**Comment by Brandejs** [comment]
Hi, Do you have any angular.json in apps/ionic-xx folder? Im running in issue that project does not exist

```
yarn run ionic.app.ios.live
$ cd apps/ionic-loowner && ionic capacitor run ios --livereload --address=0.0.0.0
> ng run app:serve --host=0.0.0.0 --port=8100
[ng] An unhandled exception occurred: Project does not exist.
[ng] See "/private/var/folders/ht/w9ntbbr90q32bkg2lcqdj8hw0000gp/T/ng-mvqGa4/angular-errors.log" for further details.

[ERROR] ng has unexpectedly closed (exit code 127).
        
```

**Comment by Jason-Schroeder** [comment]
I have a workspace.json file and an angular.json file within the ionic app root directory. Both have the same content. This was done to allow the ionic commands to run while still allowing the nx commands to work as expected

**Comment by radarsu** [comment]
Same problem. Cannot run live reload from latest xplat workspace, because angular.json is not present in ionic project directory itself.

I solved the problem by creating redundant angular.json, but that's far from ideal.

**Comment by NathanWalker** [comment]
This will be solved when Nrwl merges [this pr](https://github.com/nrwl/nx/pull/2811)
