### ISSUE TITLE
Ionic Production build fails with. Please add a @NgModule annotation. 

### ISSUE THREAD

**Issue by chrene** [nstudio/xplat#149]
I added a clean ionic app to an nx workspace, and tried to build it with the production flag.

This is the error I'm getting.
```
ERROR in Unexpected value 'MyworkspaceIonicCoreModule in myworkspace/xplat/ionic/core/core.module.ts' imported by the module 'CoreModule in myworkspace/apps/ionic-ionic/src/app/core/core.module.ts'. Please add a @NgModule annotation.
```

**Module it complains about**
```
import { NgModule } from '@angular/core';

// libs
import { MyworkspaceIonicCoreModule } from '@myworkspace/ionic';

@NgModule({
  imports: [MyworkspaceIonicCoreModule]
})
export class CoreModule {}

```

**Production configuration:**

```
"configurations": {
  "production": {
    "fileReplacements": [
      {
        "replace": "apps/ionic-ionic/src/environments/environment.ts",
        "with": "apps/ionic-ionic/src/environments/environment.prod.ts"
      }
    ],
    "optimization": true,
    "outputHashing": "all",
    "sourceMap": false,
    "extractCss": true,
    "namedChunks": false,
    "aot": true,
    "extractLicenses": true,
    "vendorChunk": false,
    "buildOptimizer": true,
    "budgets": [
      {
        "type": "initial",
        "maximumWarning": "2mb",
        "maximumError": "5mb"
      }
    ]
  }
}
```

This error happens when I use `aot: true` and `buildOptimizer: true`.

**Comment by chrene** [comment]
Apparently this happens when the apps contain `node_modules`. Removing them and installing the the node modules in the root instead and seemed to fix the problem. 

Then change the `apps/app-name/package.json` to point to the root like this. 

```
"dependencies": {
   "dependency": "file:../../node_modules/dependency"
}
```

instead of

```
"dependencies": {
   "dependency": "~1.0.0"
}
```

**Comment by dharapatel06** [comment]
I am getting the same error.
Project environment: a 'nx' workspace with 1 angular app and 1 ionic app generated using xplat tool.
The package.json file points to the root as depicted in previous comment. But node-modules directory still exists inside 'ionic-app'. Capacitor dependencies are added specific to 'ionic-app' package.json. 

Both Angular app and Ionic app uses a shared library. Angular app works great.

While building app for production with --aot enabled, it fails. 
Build failing error: 
`ERROR in Unexpected value 'SharedLibModule in ../projectname/libs/shared-lib/src/lib/shared-lib.module.ts' imported by the module 'HomePageModule in ../projectname/apps/ionic-app/src/app/home/home.module.ts'. Please add a @NgModule annotation.`

After setting --aot=false & --optimization=true, production build passes successfully. But when running the iOS or Android App in respective IDE, App displays blank screen after showing splash screen with error message in console as follows:

```
⚡️  [error] - ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'this.marshal.init')
init@capacitor://localhost/main-es2015.826bb9c540753f57ca79.js:1:294936
```
Ionic App production build works great after setting 'aot' and 'optimization' to 'false'. Apps works as expected with this settings in angular.json.

Is there anything wrong here?

**Comment by Vatsalya-singhi** [comment]
Hi, I am facing the same exact issue on ionic 5 builds and the packages are on latest versions. Clearing the node_modules folder then re-installing also didn't help. Can some please look into it. Thanks in advance.
