### ISSUE TITLE
The template specified for component HeaderComponent is not a string

### ISSUE THREAD

**Issue by Cselt** [nstudio/xplat#151]
After creating a new workspace and generating a new Angular application the app can't start because of a runtime error:

```
Uncaught Error: The template specified for component HeaderComponent is not a string
    at syntaxError (compiler.js:2175)
    at DirectiveNormalizer.normalizeTemplate (compiler.js:17649)
    at CompileMetadataResolver.loadDirectiveMetadata (compiler.js:19820)
    at compiler.js:25829
    at Array.forEach (<anonymous>)
    at compiler.js:25828
    at Array.forEach (<anonymous>)
    at JitCompiler._loadModules (compiler.js:25825)
    at JitCompiler._compileModuleAndComponents (compiler.js:25805)
    at JitCompiler.compileModuleAsync (compiler.js:25767)
```

### Repro steps:

Create a new nx workspace:
```
npx create-nx-workspace myworkspace

// Choose 'Empty'
// Choose 'Nx' cli when asked
```

Then add xplat to it:
```
cd myworkspace
npm i -D @nstudio/xplat
```

Generate an angular web app:
```
nx g app test-app
// Choose 'web' as the type of the app
// Choose 'angular' as the frontend
// Choose Yes for using xplat supporting architecture
// Hit enter when it asks for directory
// Choose 'SASS' as the stylesheet format
```

Start web app serve with `npm run start.web.test-app`
Then open browser on `http://localhost:4200`
You will see a white page with the specified error in the console.

**Global package versions**
Angular CLI: 8.3.3
Node: 10.16.3
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.3
@angular-devkit/core         8.3.3
@angular-devkit/schematics   8.3.3
@schematics/angular          8.3.3
@schematics/update           0.803.3
@nrwl/cli                             8.5.1
@nrwl/nx                          7.8.7
rxjs                         6.4.0

Windows 10

**Comment by NathanWalker** [comment]
Fixed in latest version (you may try setting up a new workspace or clearing node_modules and ensure you have xplat 8.0.7 installed - I also updated getting started guide and removed the `create-xplat-workspace` binary since it was unnecessary and better to start with Nx proper and add xplat tooling into it. It also helps alleviate future changes Nx may introduce which could transiently break any shorthand binary like that. Lemme know if you have any further issues.

**Comment by Cselt** [comment]
Thanks @NathanWalker 🥇
Can't wait to start using xplat, and share as many code as I can 😁
