### ISSUE TITLE
Changing nx with ng

### ISSUE THREAD

**Issue by NicoForce** [nstudio/xplat#153]
I have succesfully generated a project with xplat, as I want to use an angular website and an ionic project both in the xplat architecture.

However, running ionic in develop mode requires ng, else ionic serve doesnt work, and I don't know how to use nx for this task.

Is it possible to change projects generated with nx to use ng? and how?

**Comment by NathanWalker** [comment]
Yes! You can actually just rename the root workspace.json to angular.json and ‘ng’ should work normally.

**Comment by NathanWalker** [comment]
If you use the scripts in the package.json you can also switch those from ‘nx’ to ‘ng’.
The Nx cli is from what I understand intended to work same in either case however there may be some growing pains with it at moment. But can always do as suggested here by renaming workspace.json and should work.

**Comment by NicoForce** [comment]
@NathanWalker While changing the workspace.json to angular.json and changing an 'nx serve' to 'ng serve', I'm getting the following error.

> ERROR in No NgModule metadata found for 'AppModule'.

Pardon me if it's a newcomer mistake as I'm new to angular.

**Comment by NathanWalker** [comment]
If this is a workspace you don’t mind sharing you could invite me to it and could take a look tomorrow. You could invite my github handle as a contributor if you push your workspace to github or just zip it up and post a link to download. Given the sometimes varied subtle changes make to their workspaces that may be best way for me to help.

**Comment by NicoForce** [comment]
I think it's public, this is my [repo](https://github.com/NicoForce/reservoFront) on dev branch.

I would appreciate it if you take a look tomorrow, as it's 1:30 a.m. here, I'll sleep as well.

**Comment by NathanWalker** [comment]
Ok perfect, here's the fix:
https://github.com/NicoForce/reservoFront/pull/1

If anyone else comes across this issue, please refer to the above PR as seems to only affect Ionic Angular projects.

**Comment by NicoForce** [comment]
Thanks for your help.

**Comment by NicoForce** [comment]
May I ask what the AngularCompiler options you added do? I kind of don't understand why are those being added.

**Comment by NathanWalker** [comment]
Sure thing theres a number of options you can pass to the angular compiler for advanced options (like even enabling the new `Ivy` renderer that way). In this case it helps the compiler know exactly where the app module is. You can also try removing that and building again as may work with just the dependency changes alone. However I left it just for good measure as it really doesn't hurt.

**Comment by NathanWalker** [comment]
Here's a more thorough and proper explanation:
https://angular.io/guide/angular-compiler-options
