### ISSUE TITLE
[Question] How to upgrade to electron 7 

### ISSUE THREAD

**Issue by mivoe** [nstudio/xplat#162]
I just tried to upgrade package.json: 
`    "electron": "7.0.0",`

npm install was fine, but npm run start.electron.{app-name} gives
![grafik](https://user-images.githubusercontent.com/57790003/68925904-7ea45d80-0784-11ea-9cf1-08359dd01333.png)

and 
![grafik](https://user-images.githubusercontent.com/57790003/68925926-8bc14c80-0784-11ea-8813-576057014939.png)

Any ideas?

**Comment by NathanWalker** [comment]
We're going to do several upgrades to packages over next week or so and will see if we can bump to electron 7.

**Comment by vladimirdrayling** [comment]
I've updated the electron version and adjusted jest [https://github.com/vladimirdrayling/xplat-starter](xplat-starter)

**Comment by skorunka** [comment]
Hello, any update on this? Thank you.

**Comment by NathanWalker** [comment]
@skorunka hi - Electron 7 support is now in xplat `8.1.1`. Huge thanks to @vladimirdrayling for the repo which the electron generator now uses (including the nice additions he added 👍 )

**Comment by sebastiandg7** [comment]
Thanks @NathanWalker. Is there any update guide to install xplat 8.1.1 (or any new release)?

**Comment by NathanWalker** [comment]
@sebastiandg7 we’ll add a section to the site docs about this. Briefly this is the steps to ordinarily take:
```
// always update Nrwl Nx first
ng update @nrwl/schematics // if on old
ng update @nrwl/workspace // if newer 8+

// update xplat 
ng update @nstudio/schematics // if on old
ng update @nstudio/xplat // if newer 8+

When not using Angular at all with any integration then it’s more manual with updating dependency versions.

**Comment by sebastiandg7** [comment]
@NathanWalker the following commands worked in a Nx cli workspace
```bash
$ nx migrate @nrwl/workspace
$ ng update @nstudio/xplat // With angular installed in the workspace (for the cli)
```
@nstudio/* dependencies were updated. However, frameworks versions such as nativescript, electron etc remain the same. How can I update the nativescript/electron version of an app?

**Comment by NathanWalker** [comment]
@sebastiandg7 We can add a migration for Electron 7 and {N} 6.3. There's a migration in from earlier {N} versions to 6.2 but we'll add some for those other versions by next week alongside some other generators we have been planning for the {N} side.

**Comment by sebastiandg7** [comment]
@NathanWalker great! It would be nice if you add those migrations whenever a new framework version is supported in a Xplat release.
