### ISSUE TITLE
Failing to start electron app placed in a directory

### ISSUE THREAD

**Issue by joelmuskwe** [nstudio/xplat#166]
**Expected Result**
Electron app to open when run.

**Current Behaviour**
```
yarn run v1.19.2
warning package.json: "dependencies" has dependency "@nstudio/xplat" with range "^8.0.13" that collides with a dependency in "devDependencies" of the same name with version "8.0.13"
warning package.json: "dependencies" has dependency "@nrwl/angular" with range "^8.8.2" that collides with a dependency in "devDependencies" of the same name with version "~8.8.0"
warning package.json: "dependencies" has dependency "@nstudio/electron" with range "^8.0.13" that collides with a dependency in "devDependencies" of the same name with version "8.0.13"
$ npm run prepare.electron.desktop-app && npm-run-all -p serve.electron.desktop-app.target serve.electron.desktop-app
npm WARN lifecycle The node binary used for scripts is /var/folders/xr/7cp2hsfd139b6tx_t_tjysfw0000gn/T/yarn--1574687993525-0.15629264163149914/node but npm is using /usr/local/Cellar/node@12/12.13.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> demo-suite@0.0.0 prepare.electron.desktop-app /Users/joelmuskwe/Projects/workspace/demo-suite
> npm run postinstall.electron && tsc -p apps/electron-desktop-app/tsconfig.json

npm WARN lifecycle The node binary used for scripts is /var/folders/xr/7cp2hsfd139b6tx_t_tjysfw0000gn/T/yarn--1574687993525-0.15629264163149914/node but npm is using /usr/local/Cellar/node@12/12.13.1/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> demo-suite@0.0.0 postinstall.electron /Users/joelmuskwe/Projects/workspace/demo-suite
> node tools/electron/postinstall

error TS5058: The specified path does not exist: 'apps/electron-desktop-app/tsconfig.json'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo-suite@0.0.0 prepare.electron.desktop-app: `npm run postinstall.electron && tsc -p apps/electron-desktop-app/tsconfig.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo-suite@0.0.0 prepare.electron.desktop-app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joelmuskwe/.npm/_logs/2019-11-25T13_19_55_697Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Log File
[2019-11-25T13_19_55_697Z-debug.log](https://github.com/nstudio/xplat/files/3886825/2019-11-25T13_19_55_697Z-debug.log)

**Steps taken to reproduce error**
1. yarn create nx-workspace
-> demo-suite
-> empty workspace
-> angular-cli

2. cd demo-suite

3. ng add @nrwl/angular
-> jest
-> cypress

4. ng g @nrw/angular:application --directory admin desktop
-> scss
-> routing: true

5. ng add @nstudio/xplat
-> not right now
-> not right now

6. ng add @nstudio/web-angular

7. ng add @nstudio/electron

8. ng g app
-> desktop-app
-> electron _(app type)_
-> angular _(framework)_
-> no _(xplat supporting architecture)_
-> admin-desktop _(name of web app)_
-> admin _(directory)_

9. yarn start.electron.desktop-app

**Comment by vladimirdrayling** [comment]
@joelmuskwe can you provide the repo?

**Comment by joelmuskwe** [comment]
The [Repo](https://github.com/joelmuskwe/demo-suite)

**Comment by vladimirdrayling** [comment]
@joelmuskwe, I've created the [pull request](https://github.com/joelmuskwe/demo-suite/pull/1).

For some reason the schematic generator can't handle sub folders. Hope the authors of xplat will fix it. But for now, don't use sub folders, as it leads to incorrect paths in `angular.json` and in `package.json`. (If you need the subfolders anyway, then adjust those paths manually)

**Comment by vladimirdrayling** [comment]
@joelmuskwe forgot to mention:

> **Note:** We recommend the following options when creating your Nx workspace:
> 
> Choose `Empty`
> Choose `Nx` cli
>
> [Xplat documentation](https://nstudio.io/xplat/getting-started/getting-started)

**Comment by joelmuskwe** [comment]
@vladimirdrayling thanks for the reply, my problem is i have an application that was based on nx using angular cli and not on Extensible CLI for JavaScript and TypeScript applications. was hoping to use xplat in it. coz after creating workspace based on nx cli i am failing to add @nwrl/angular for the workspace to also support angular the nx way.

**Comment by joelmuskwe** [comment]
@vladimirdrayling thank you for the assist in my demo-suite now i know what changes i will need to do to make it compatible with my existing project.
