### ISSUE TITLE
Nativescript TypeError: Cannot read property 'browser' of undefined

### ISSUE THREAD

**Issue by dmitryr117** [nstudio/xplat#168]
This does not occur if I create NS app without supporting xplat architecture. However if I use xplat supporting architecture the following occurs:

When using:
npm run start.nativescript.test.android

The app loads into an android emulator running android-28 avd:

Installing on device emulator-5554...
Successfully installed on device with identifier 'emulator-5554'.
Restarting application on device emulator-5554...
Successfully synced application org.nativescript.test on device emulator-5554.

And then fails inside emulator with:

System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'browser' of undefined
System.err: File: (file:///node_modules/pbkdf2/lib/default-encoding.js:3:11)
 ...

I looked online, but there seems to be only one post on Stackoverflow and nothing else. 
Does anyone have any ideas as to how to solve this?

**Comment by dmitryr117** [comment]
Ohh. Never mind. I was testing some things with Angular with the same xplat setup monorepo earnier. There is an Ngrx Store code sitting in 'lib' folder which could save redux state into the browser local storage. I am pretty sure this is what caused the issue because xplat architecture would have imported that code and there is no browser local storage when using NS.

**Comment by NathanWalker** [comment]
Good to know you solved it, yes raw browser api's should not be used in executable Js intended for {N}
