### ISSUE TITLE
Generate feature - Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by pavelekNET** [nstudio/xplat#175]
Hi,

when I follow "Getting started guide" step by step everyting works fine. When I want to generate Feature with `nx g feature --name=ukulele --platforms=web` i got `Cannot read property 'toString' of null`

package json:

> {
  "name": "myworkspace",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "nx": "nx",
    "start": "nx serve",
    "build": "nx build",
    "test": "nx test",
    "lint": "nx workspace-lint && nx lint",
    "e2e": "nx e2e",
    "affected:apps": "nx affected:apps",
    "affected:libs": "nx affected:libs",
    "affected:build": "nx affected:build",
    "affected:e2e": "nx affected:e2e",
    "affected:test": "nx affected:test",
    "affected:lint": "nx affected:lint",
    "affected:dep-graph": "nx affected:dep-graph",
    "affected": "nx affected",
    "format": "nx format:write",
    "format:write": "nx format:write",
    "format:check": "nx format:check",
    "workspace-schematic": "nx workspace-schematic",
    "dep-graph": "nx dep-graph",
    "help": "nx help",
    "clean": "npx rimraf hooks node_modules package-lock.json && npm i",
    "start.web.sablonyzer-web": "nx serve web-sablonyzer-web"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.0",
    "@angular/common": "^8.2.0",
    "@angular/compiler": "^8.2.0",
    "@angular/core": "^8.2.0",
    "@angular/forms": "^8.2.0",
    "@angular/platform-browser": "^8.2.0",
    "@angular/platform-browser-dynamic": "^8.2.0",
    "@angular/router": "^8.2.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.4.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@nrwl/workspace": "8.11.2",
    "@nstudio/xplat": "^8.1.1",
    "@types/node": "~8.9.4",
    "dotenv": "6.2.0",
    "eslint": "6.1.0",
    "prettier": "1.18.2",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.5.3",
    "@nstudio/angular": "8.1.1",
    "@nstudio/web-angular": "8.1.1",
    "@nstudio/web": "8.1.1",
    "@nrwl/angular": "~8.8.0",
    "@angular/compiler-cli": "^8.2.0",
    "@angular/language-service": "^8.2.0",
    "@angular-devkit/build-angular": "^0.803.14",
    "codelyzer": "~5.0.1",
    "jest-preset-angular": "7.0.0",
    "@nrwl/jest": "8.11.2",
    "jest": "24.1.0",
    "@types/jest": "24.0.9",
    "ts-jest": "24.0.0",
    "cypress": "3.6.1",
    "@nrwl/cypress": "8.11.2"
  },
  "xplat": {
    "prefix": "myworkspace",
    "framework": "angular"
  }
}

**Comment by NathanWalker** [comment]
Thanks @pavelekNET - I'll check if a patch version in your package is affecting this.

**Comment by NathanWalker** [comment]
@pavelekNET I realized that you were running the command without the angular prefix. The `feature` generator is supported in angular workspaces and doesn't hang off the general `@nstudio/xplat` namespace like `app` and `xplat` init generation.

You can use this command and find it will work for you to generate platform specific features for angular:
```
nx g @nstudio/angular:feature ukulele --platforms web --dry-run
CREATE libs/features/ukulele/ukulele.module.ts (136 bytes)
CREATE libs/features/ukulele/index.ts (34 bytes)
CREATE xplat/web/features/ukulele/ukulele.module.ts (376 bytes)
CREATE xplat/web/features/ukulele/index.ts (64 bytes)
CREATE xplat/web/features/ukulele/components/index.ts (165 bytes)
CREATE xplat/web/features/ukulele/components/ukulele/ukulele.component.html (22 bytes)
CREATE xplat/web/features/ukulele/components/ukulele/ukulele.component.ts (268 bytes)
UPDATE libs/features/index.ts (49 bytes)
UPDATE xplat/web/features/index.ts (49 bytes)

NOTE: The "dryRun" flag means no changes were made.
```

**Comment by pavelekNET** [comment]
When i run:

`nx g @nstudio/angular:feature ukulele --platforms web --dry-run`

I still get the same result

`Cannot read property 'toString' of null`

**Comment by NathanWalker** [comment]
@pavelekNET possible to share project or at least the package.json?
Did you clean all node_modules in project and npm install fresh?

**Comment by NathanWalker** [comment]
Also curious what your project structure looks like - possible to post screenshot of libs and xplat folders if unable to share project?

**Comment by tzoratto** [comment]
Hi, a bit late maybe but I had the same issue because I had deleted the libs/features/index.ts file. (Add the file back to fix the issue)

I still don't understand why generating a platform specific (web in this case) feature ends up creating a feature in the platform agnostic libs folder. In my understanding, creating a feature with --platforms web should only create files under xplat/web/features and not under libs/features.

But I'm a total newbie in the xplat world, I'm probably wrong ! Can someone explain this behavior ?

Thanks
