### ISSUE TITLE
Upgrade to NX9/Angular9

### ISSUE THREAD

**Issue by pegaltier** [nstudio/xplat#178]
Is it possible to upgrade the version of the dependencies to use the latest release of NX and Angular?

**Comment by NathanWalker** [comment]
@pegaltier We have not updated yet however please feel free to update Nx and Angular and report if any issue. Within the next week we'll be doing some upgrade passes with several components to see if there are any issues that need to be cleared.

**Comment by NathanWalker** [comment]
@pegaltier Angular 9 with Ivy now works with {N} here https://github.com/NativeScript/nativescript-angular/pull/2124 and we can now update the tooling to support latest Nx and v9. Putting in progress.

**Comment by abcfoundry** [comment]
thoughts on progress/timeframe?  Starting a new project and would like to make this the baseline.

cheers,
AJ

**Comment by NathanWalker** [comment]
@abcfoundry Thanks - we will probably release Angular 9 support in next 2-3 days even if some of the dependencies needed haven't published yet (ie, nativescript-angular); we would instead have dep's link to a remote .tgz or other github for now. Also it's possible we can release support initially allowing developers to work with Angular 9 even if Ivy wasn't fully enabled yet for all the platforms (namely {N}) - main thing to clear is the xplat architecture which used "spread" on various arrays which Ivy doesn't like.

**Comment by NathanWalker** [comment]
@abcfoundry this pr has all the changes needed, just one dependency the architecture uses that we need to update which I will plan to do by eod Monday to get these updates out:
https://github.com/nstudio/xplat/pull/179

**Comment by NathanWalker** [comment]
https://github.com/nstudio/xplat/pull/179#issuecomment-594163584
