### ISSUE TITLE
[Bug] Nrwl/NX + Xplat Lint Error

### ISSUE THREAD

**Issue by johannesschobel** [nstudio/xplat#190]
Dear @NathanWalker ,

i just tried the new 9.0.2 version of xplat to work with ionic 5 applications.
This is just great - thanks for your awesome support :+1: 

However, i stumbled upon an issue in combination with nrwl: Linting fails for some of the generated libs!

This is, because some of the referenced `tsconfig` files in the `angular.json` configuration file are missing.

# Steps to reproduce

1) setup a default nrwl workspace
2) add xplat as described on the website
3) add an ionic 5 application
4) run `npm run affected:lint`

For me, this outputs something like this:
```bash
// ... lots of output here

> ng run xplat:lint 
Linting "xplat"...
An unhandled exception occurred: error TS5058: The specified path does not exist: '/path/to/root/testing/tsconfig.xplat.json'.

See "/tmp/ng-AwOuPH/angular-errors.log" for further details.

> ng run libs:lint 
Linting "libs"...
An unhandled exception occurred: error TS5058: The specified path does not exist: '/path/to/root/testing/tsconfig.libs.json'.

See "/tmp/ng-4jXbHQ/angular-errors.log" for further details.

> ng run ionic-app:lint 
Linting "ionic-app"...
An unhandled exception occurred: error TS5058: The specified path does not exist: '/path/to/root/apps/ionic-app/e2e/tsconfig.json'.

See "/tmp/ng-tBywhb/angular-errors.log" for further details.
```

the files that are reported are actually missing. For now i am just removing those lines in the `angular.json` file, however, it would be good to add the latter. What do you think?

all the best and thanks for your support,
Johannes

**Comment by NathanWalker** [comment]
Thanks for tracking this @johannesschobel I'll take a look 👍

**Comment by NathanWalker** [comment]
fixed in latest
