### ISSUE TITLE
Base configuration of NS + web app without using xplat structure causes Zone.js error

### ISSUE THREAD

**Issue by dtomaszewski** [nstudio/xplat#192]
I wanted to try to have xplat basic configuration without structure and it seems that it's not working :

`npx create-nx-workspace myworkspace`
`yarn global add @nrwl/cli`
`nx generate app nativescript`
`nx generate app web`

then 
`start.nativescript.<appname>.ios`

produces error:

![Screenshot 2020-04-21 at 12 11 42](https://user-images.githubusercontent.com/4403684/79854208-65ee4280-83c9-11ea-8485-a436d616429c.png)

It looks like there is some conflict with loading zones, I tried to look at it a bit but it was not very clear as I have 2d of experience with NS libs ;) Web app however works fine.

_Originally posted by @dtomaszewski in https://github.com/nstudio/xplat/issues/191#issuecomment-617087140_

**Comment by NathanWalker** [comment]
Thanks for heads up @dtomaszewski - answered in the other issue but we'll get the vanilla (non-structure) generator updated.

**Comment by NathanWalker** [comment]
Fixed with `9.0.3`, thanks again for reporting.
