### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by dalepo** [nstudio/xplat#200]
Currently running on a capacitor ionic-angular project:
`nx g feature my-feature --platforms ionic`
It gives:
```
✔ Packages installed successfully.
Cannot read property 'toString' of null
```

Tried running `nx g @nstudio/angular:feature viajes --platforms ionic --dry-run` which gave me the same result.

I currently have my libs folder with only a shared module, I need to do a new features index/folder which exports my-feature through an index. Why is this failing?

Dependencies
```
    "@nstudio/xplat": "^9.0.3",
    "@nrwl/workspace": "9.3.0",
    "@nrwl/angular": "~9.2.2",
    "@angular/cli": "~9.1.7",
    "@angular/compiler-cli": "~9.1.9",
```

**Comment by ildemartinez** [comment]
same issue to me

![imagen](https://user-images.githubusercontent.com/1641352/90558304-24fe1300-e19c-11ea-8e5c-a4048f2cfc3d.png)

  "dependencies": {
    "@angular/animations": "^10.0.10",
    "@angular/cdk": "^10.1.2",
    "@angular/common": "^10.0.10",
    "@angular/compiler": "^10.0.10",
    "@angular/core": "^10.0.10",
    "@angular/fire": "^6.0.2",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "^10.0.10",
    "@angular/material": "^10.1.2",
    "@angular/platform-browser": "^10.0.10",
    "@angular/platform-browser-dynamic": "^10.0.10",
    "@angular/router": "^10.0.10",
    "@capacitor/core": "^2.4.0",
    "@ionic-native/core": "^5.28.0",
    "@ionic-native/splash-screen": "^5.28.0",
    "@ionic-native/status-bar": "^5.28.0",
    "@ionic/angular": "~5.0.7",
    "@nestjs/common": "^7.0.0",
    "@nestjs/core": "^7.0.0",
    "@nestjs/platform-express": "^7.0.0",
    "@nestjs/swagger": "^4.5.12",
    "@nrwl/angular": "10.0.8",
    "@swimlane/ngx-datatable": "^17.1.0",
    "angular-calendar": "^0.28.16",
    "chartist": "^0.11.4",
    "class-transformer": "^0.3.1",
    "class-validator": "^0.12.2",
    "config": "^3.3.1",
    "cookie-parser": "^1.4.5",
    "csurf": "^1.11.0",
    "helmet": "^4.1.0",
    "ng-multiselect-dropdown": "^0.2.10",
    "ngx-perfect-scrollbar": "^10.0.1",
    "ngx-spinner": "^10.0.1",
    "nodemailer": "^6.4.11",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~6.5.5",
    "rxjs-compat": "^6.6.2",
    "rxjs-tslint": "^0.1.8",
    "zone.js": "^0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/architect": "~0.901.0",
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular-devkit/core": "~9.1.0",
    "@angular-devkit/schematics": "~9.1.0",
    "@angular/cli": "^10.0.6",
    "@angular/compiler-cli": "^10.0.10",
    "@angular/language-service": "^10.0.10",
    "@ionic/angular-toolkit": "^2.2.0",
    "@nestjs/schematics": "^7.0.0",
    "@nestjs/testing": "^7.0.0",
    "@nrwl/angular": "~9.2.2",
    "@nrwl/cypress": "10.0.8",
    "@nrwl/eslint-plugin-nx": "10.0.10",
    "@nrwl/jest": "10.0.8",
    "@nrwl/nest": "10.0.8",
    "@nrwl/node": "10.0.8",
    "@nrwl/workspace": "^10.0.12",
    "@nstudio/angular": "9.0.4",
    "@nstudio/electron": "9.0.4",
    "@nstudio/electron-angular": "9.0.4",
    "@nstudio/ionic": "9.0.4",
    "@nstudio/ionic-angular": "9.0.4",
    "@nstudio/web-angular": "9.0.4",
    "@nstudio/xplat": "^9.0.4",
    "@types/jasmine": "~3.5.9",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "25.1.4",
    "@types/node": "~8.9.4",
    "@typescript-eslint/eslint-plugin": "2.19.2",
    "@typescript-eslint/parser": "2.19.2",
    "codelyzer": "~5.1.0",
    "cypress": "^4.1.0",
    "dotenv": "6.2.0",
    "electron": "^7.0.1",
    "electron-builder": "^20.44.4",
    "electron-installer-dmg": "~3.0.0",
    "electron-packager": "~14.1.0",
    "electron-rebuild": "~1.8.6",
    "electron-reload": "~1.5.0",
    "electron-store": "~5.1.0",
    "electron-updater": "~4.2.0",
    "eslint": "^6.8.0",
    "eslint-config-prettier": "6.0.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.0",
    "jest": "25.2.3",
    "jest-preset-angular": "8.1.2",
    "karma": "~4.4.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.1",
    "karma-jasmine": "~3.1.1",
    "karma-jasmine-html-reporter": "^1.5.2",
    "npm-run-all": "^4.1.5",
    "prettier": "2.0.4",
    "ts-jest": "25.2.1",
    "ts-node": "~7.0.0",
    "tslint": "~6.0.0",
    "typescript": "^3.9.7",
    "wait-on": "~3.3.0"
  },
