### ISSUE TITLE
nx generate @nstudio/xplat:feature adds the feature in the src and should be apps

### ISSUE THREAD

**Issue by abcfoundry** [nstudio/xplat#202]
using schematics .. nx generate @nstudio/xplat:feature

nx generate @nstudio/xplat:feature --name=feature-name --onlyProject --platforms=nativescript,web --projects=app-nativescript,app-web --routing

This causes the features to be created in src > features.  SHOULD be src > apps > features

NOTE the is for the web app only not the nativescript app.  It is all good

cheers,

**Comment by abcfoundry** [comment]
any update on this ?  Its a lot of work to fix after running the schematics ..  
example 
nx generate @nstudio/angular:feature --name=dashboard --onlyProject --platforms=nativescript,web --projects=xxx-nativescript,xxx-web --routing <

but a lot less than not using ... thanks

**Comment by NathanWalker** [comment]
For those coming across this, when using `--onlyProject` with `--projects` just omit **platforms** for example:

```
nx generate @nstudio/xplat:feature --name=feature-name --onlyProject --projects=app-nativescript,app-web --routing
```

Feature generator target projects *or* shared platform code, not both.
