### ISSUE TITLE
Angular 10 support

### ISSUE THREAD

**Issue by ceelian** [nstudio/xplat#203]
Will there be an xplat version which supports angular 10 & nativescript and if so when approximately. Thx.

**Comment by antoinepairet** [comment]
Please see this issue on the `nx` repo: https://github.com/nrwl/nx/issues/3232

**Comment by ceelian** [comment]
@antoinepairet the issue in nx was closed, does that mean that xplat supports angular 10 automatically now?

**Comment by benpsnyder** [comment]
Hoping to get xplat compatible with Nx 10 / Angular 10

**Comment by ceelian** [comment]
Looks like it is already done in PR #208

**Comment by NathanWalker** [comment]
Thanks @ceelian - that's correct - xplat ~10.0.0 is out and supports angular 10 (as well as the upcoming {N} 7 release due out next week).
