### ISSUE TITLE
Confusing generation process

### ISSUE THREAD

**Issue by ericjeker** [nstudio/xplat#204]
I started to use xplat today as we are going to have a new Ionic project to create a it will share many common libraries with other Ionic project and maybe some Angular and Nest projects as well.

I must say, generating an xplat app was quite confusing to me as it does a lot of magic under the hood that is not really necessary to me. Please bear with me. This is just my opinion.

Below is my setup:

![image](https://user-images.githubusercontent.com/979397/86924145-a4da9b80-c161-11ea-8c85-5907623b3133.png)

As you can see, I would like to name my app "app" but it is then prefixed with "ionic" for no apparent reason, or maybe there is one? So then if I do `nx serve app` or `nx g remove app` I obviously receive an error because "app" doesn't exist.

![image](https://user-images.githubusercontent.com/979397/86925378-6645e080-c163-11ea-940a-c4944d746b31.png)

By following the getting-started on your site, we get that error on the last line of the tutorial because `nx serve appname` doesn't match what we previously typed.

Then there is that question about what directory the app should be generated in. Here I first answered "app" but then it create a sub-directory `app/ionic-app/` which is even more confusing because this doesn't match with anything I answered before.

The behavior I personally expect is: 

- if I name my app "app", it should be named "app" and nothing else
- if I want my app to be installed in a directory named `app`, that should be the case, and it shouldn't be in a sub-directory like `app/app/`. Also, by default, the directory should be named like the name of the application.

Also in my opinion, the default answer to "Use xplat supporting architecture?" should be: No. I tried to install xplat in an existing Angular/Nest project with existing libraries and it made a mess in my `libs/` folder. Maybe you could setup these libs in a sub-directory named `xplat/` or something.

Obviously, now that I know all that, I won't make the mistakes again, but I wanted to give you my feedback on a fresh use of xplat. Let me know if I completely missed the point.

**Comment by Apsistec** [comment]
Thanks for the help, been stuck till now, trying to create an "ionic app" in the apps folder.

**Comment by NathanWalker** [comment]
It is now all self contained in single `xplat` folder in libs with Nx library separation with v11.
