### ISSUE TITLE
maybe im slow but cant seem to generate a service file for my angular app with nx after adding xplat

### ISSUE THREAD

**Issue by djflip2016** [nstudio/xplat#205]
after adding xplat to my existing nx workspace i can no longer use nx g service command

**Comment by dmitryr117** [comment]
Hello. It seems documentation could use some revamping. Anyway to create a service you have to specify the schematic to be used to add it. For example for services this schematic is **@nstudio/angular:service**.
First you can use a schematic help method.

`nx generate @nstudio/angular:service --help`

This is where you will see all the possible options you can use to create service. I always use --dryRun option to see what files will be generated before actually running it and generating all the files for real. Same thing goes for generating components and other things. Component example:

`nx generate @nstudio/angular:component --help`

**Comment by dmitryr117** [comment]
@djflip2016  Here. I made a video about this. https://youtu.be/U1gJZP4YEKk

**Comment by NathanWalker** [comment]
Thank you @dmitryr117 this is incredibly helpful.  I'm in process of updating schematics to latest v10 of Nx now and Angular 10 as well as latest {N}. We're also splitting the xplat mode (dev modes) into it's own package @nstudio/focus so it could be installed even outside of xplat tooling for those wanting to just use dev modes in Nx for more broad use cases.

**Comment by dmitryr117** [comment]
Hey there @NathanWalker . Those are some exiting developments. I guess I will make some new instruction vids once the version 10 release comes around. I was also thinking of making a contributor series where I can show people how to set up a contributor development environment, testing and that sort of thing.

**Comment by NathanWalker** [comment]
Contributing is always good material to cover as schematics are not intuitive on the surface and understanding a good development workflow with them is always best place to start. Thanks for reaching out via email, we'll setup a zoom session to review some other topics.
