### ISSUE TITLE
Cannot read property 'content' of null

### ISSUE THREAD

**Issue by davidpodhola** [nstudio/xplat#206]
Steps to reproduce on Ubuntu 20.04, _node 14_ (but also tested on _node 12_ and with angular feature added first to the workspace).

```
cd /tmp
npx create-nx-workspace myworkspace
```
choose **empty** and  **Nx**
```
cd myworkspace
yarn add --dev @nstudio/xplat
yarn nx generate app
```
choose **mobile**, **nativescript**, **Yes**, **angular**, **Yes**, **blah**.

You will get `Cannot read property 'content' of null`.

What am I please doing wrong? Thanks!

![Screenshot from 2020-07-21 22-28-27](https://user-images.githubusercontent.com/436605/88103685-a2386700-cba1-11ea-92ee-8919b7d05d18.png)

**Comment by Apsistec** [comment]
### Same issue for me on windows using VS Code and Git Bash, installing Ionic app and web, both with Angular

**Comment by DanielSofomo** [comment]
Still an issue for me, even after saying no to xplat arch

**Comment by dmitryr117** [comment]
Same thing is happening when trying to set up an angular project. Worckspace version 10.0.6. Xplat version 9.0.4.

? What name would you like for this app? test
? What type of app would like to create? web             [Web app]
? Would you like to configure routing for this app? Yes
? Which frontend framework should it use? angular        [Angular app]
? Use xplat supporting architecture? Yes
✔ Packages installed successfully.
? In which directory should the app be generated? 
? Which stylesheet format would you like to use? SASS(.scss)  [ http://sass-lang.com   ]
Cannot read property 'content' of null

It installs fine without Xplat supporting architecture; however Xplat supporting architecture is one of the main reasons to use Xplat.

**Comment by dmitryr117** [comment]
The culprit is detected. The error in compiled node modules is in: ./node_modules/@nstudio/xplat/src/utils/xplat.js on line 500. There may be more problem areas still, but this is one of them.

**Comment by dmitryr117** [comment]
Actually scratch that I tested some more, and it seems to be in: ./node_modules/@nstudio/xplat/src/utils/general.js starting at line 81. I added a console.log there. Core like this:

```
exports.jsonParse = jsonParse;
function getJsonFromFile(tree, path) {
    console.log('General 83', path);
    return jsonParse(tree.get(path).content.toString());
```

When trying to build a project - I got the following:

? What name would you like for this app? test2
? What type of app would like to create? web             [Web app]
? Would you like to configure routing for this app? Yes
General 83 nx.json
General 83 package.json
? Which frontend framework should it use? angular        [Angular app]
? Use xplat supporting architecture? Yes
General 83 nx.json
General 83 package.json
General 83 package.json
General 83 package.json
✔ Packages installed successfully.
? In which directory should the app be generated? 
? Which stylesheet format would you like to use? CSS
General 83 nx.json
General 83 package.json
General 83 nx.json
General 83 package.json
Xplat.js 500
General 83 nx.json
General 83 package.json
General 83 nx.json
General 83 tsconfig.json
Cannot read property 'content' of null

Looks like a problem with tree and tsconfig.json. In a new version tsconfig.json at workspace root is renamed to tsconfig.base.json

**Comment by dmitryr117** [comment]
Ok. To solve this I did a bit of a hack. Before running **npx nx generate app** I created a **tsconfig.json** file in the workspace root. The contents are as follows:
`
{
  "extends": "./tsconfig.base.json"
}
`
That's it. It should work from here. I tested in with both Angular and Nativescript installations. Seems to work fine.
