### ISSUE TITLE
Old create-nx-workspace issue

### ISSUE THREAD

**Issue by sush0408** [nstudio/xplat#207]
While Using the command **npx create-nx-workspace myworkspace** as per the getting started document [here](https://nstudio.io/xplat/getting-started/getting-started).
It may happen that user is having older version of create-nx-workspace which may cause problem.

so **npx create-nx-workspace myworkspace** can be replaced with **npx create-nx-workspace@latest myworkspace**

Just a Suggestion. :)

**Comment by NathanWalker** [comment]
Great suggestion - we'll update this in docs, definitely has caught some trouble for people not realizing they had actually installed create-nx-workspace globaly and was falling back to old version 👍
