### ISSUE TITLE
ERROR in ../../../xplat/nativescript/core/services/app.service.ts:79:21 - error TS2304: Cannot find name 'NSBundle'.

### ISSUE THREAD

**Issue by mxhgraphics** [nstudio/xplat#214]
Hi, 
I have just installed and try xplat, i can't seem to debug the fresh install of a **nativescript/angular app** this is my config:

- Windows 10
- npm --version
     6.14.8
- nx report
     nx : 10.2.1
    @nrwl/angular : 10.1.0
    @nrwl/cli : 10.2.1
    @nrwl/cypress : 10.1.0
    @nrwl/eslint-plugin-nx : 10.2.1
    @nrwl/express : Not Found
    @nrwl/jest : 10.1.0
    @nrwl/linter : Not Found
    @nrwl/nest : Not Found
    @nrwl/next : Not Found
    @nrwl/node : Not Found
    @nrwl/react : Not Found
    @nrwl/schematics : 8.12.11
    @nrwl/tao : 10.2.1
    @nrwl/web : Not Found
    @nrwl/workspace : 10.2.1
    typescript : 3.9.3

..and this is the error stack

ERROR in ../../../xplat/nativescript/core/services/app.service.ts:79:21 - error TS2304: Cannot find name 'NSBundle'.

79       versionName = NSBundle.mainBundle.objectForInfoDictionaryKey(
                       ~~~~~~~~
../../../xplat/nativescript/core/services/app.service.ts:82:21 - error TS2304: Cannot find name 'NSBundle'.

82       buildNumber = NSBundle.mainBundle.objectForInfoDictionaryKey(
                       ~~~~~~~~
../../../xplat/nativescript/core/services/app.service.ts:132:31 - error TS2552: Cannot find name 'UIDevice'. Did you mean 'Device'?

132     const deviceOrientation = UIDevice.currentDevice.orientation;
                                  ~~~~~~~~
../../../xplat/nativescript/core/services/app.service.ts:134:29 - error TS2552: Cannot find name 'UIDeviceOrientation'. Did you mean 'deviceOrientation'?

134       deviceOrientation === UIDeviceOrientation.LandscapeLeft ||
                                ~~~~~~~~~~~~~~~~~~~

  ../../../xplat/nativescript/core/services/app.service.ts:132:11
    132     const deviceOrientation = UIDevice.currentDevice.orientation;
                  ~~~~~~~~~~~~~~~~~
    'deviceOrientation' is declared here.
../../../xplat/nativescript/core/services/app.service.ts:135:29 - error TS2552: Cannot find name 'UIDeviceOrientation'. Did you mean 'deviceOrientation'?

135       deviceOrientation === UIDeviceOrientation.LandscapeRight
                                ~~~~~~~~~~~~~~~~~~~

  ../../../xplat/nativescript/core/services/app.service.ts:132:11
    132     const deviceOrientation = UIDevice.currentDevice.orientation;
                  ~~~~~~~~~~~~~~~~~
    'deviceOrientation' is declared here.
../../../xplat/nativescript/core/services/app.service.ts:139:29 - error TS2552: Cannot find name 'UIDeviceOrientation'. Did you mean 'deviceOrientation'?

139       deviceOrientation === UIDeviceOrientation.Portrait ||
                                ~~~~~~~~~~~~~~~~~~~

  ../../../xplat/nativescript/core/services/app.service.ts:132:11
    132     const deviceOrientation = UIDevice.currentDevice.orientation;
                  ~~~~~~~~~~~~~~~~~
    'deviceOrientation' is declared here.
../../../xplat/nativescript/core/services/app.service.ts:140:28 - error TS2552: Cannot find name 'UIDeviceOrientation'. Did you mean 'deviceOrientation'?

140       deviceOrientation == UIDeviceOrientation.PortraitUpsideDown


I've also notice this inside the file:
`import { LogService, PlatformLanguageToken } from '@ns-app/core';`
where the import path does not exist.

What am I missing?

**Comment by NathanWalker** [comment]
@mxhgraphics This was related to a change Nx made to use `tsconfig.base.json` instead of `tsconfig.json` at root of workspace. just released https://github.com/nstudio/xplat/releases/tag/10.2.0 which fixes it. Probably easier to just create a new workspace if new.

**Comment by mxhgraphics** [comment]
> @mxhgraphics This was related to a change Nx made to use `tsconfig.base.json` instead of `tsconfig.json` at root of workspace. just released https://github.com/nstudio/xplat/releases/tag/10.2.0 which fixes it. Probably easier to just create a new workspace if new.

Thank you very much, i will try it straight away!

**Comment by NathanWalker** [comment]
Fixed in v11
