### ISSUE TITLE
NativeScript Core module generation support 

### ISSUE THREAD

**Issue by alexziskind1** [nstudio/xplat#22]
Support generating a new NativeScript Core set of related resources according to an opinionated architectural pattern.

**Comment by NathanWalker** [comment]
We can use `xplat/nativescript` for core (aka, vanilla) integrations as well.

**Comment by vance** [comment]
I was actually curious about how xplat might wrap/use the [Nativescript Schematics](https://github.com/nativescript/nativescript-schematics). I don't see it being used under the hood by the xplat schematics.

**Comment by NathanWalker** [comment]
v8 now allows vanilla {N} app generator 🎉 `nx generate app` and follow the prompts and just don't choose a frontend framework when asked. As far as adding a xplat layer for vanilla we can talk about which pieces with vanilla would be most beneficial later.
