### ISSUE TITLE
Error running app right after install

### ISSUE THREAD

**Issue by SergeyMell** [nstudio/xplat#225]
I've installed the nx workspaces and xplat according to the docs.
Created a NativeScript-Angular application inside
However, when I try to run the installed application I get an error
```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm ERR! code ENOLOCAL
npm ERR! Could not install from "../../node_modules/nativescript-theme-core" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mell/.npm/_logs/2020-11-29T16_56_47_605Z-debug.log
Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: Command npm failed with exit code 1
```
As far as I see, the problem happens because the nativescript app `package.json` reffers to the workspace `nativescript-theme-core` module which was not installed.

I think I can fix this and create an appropriate PR if you approve.
Additionally, I think we should move from `nativescript-theme-core` to '@nativescript/theme'. Am I right? I yes, I will take this into account in my PR, if no - please, tell me what I'm missing.

**Comment by NathanWalker** [comment]
We'll stick with nativescript-theme-core until @nativescript/theme 4.0 which will support tailwind.
