### ISSUE TITLE
Unable to generate Web App

### ISSUE THREAD

**Issue by neryortez** [nstudio/xplat#23]
I have made a clean install of my workspace using the [instruccions ](https://nstudio.io/xplat/) step by step.
But the generation of the web app with `ng g app webapp` fails with `Cannot read property 'kind' of undefined`.

The generation of a NativeScript app is successful.
I have also erased the node_modules folder and reinstall the packages

I have tried to track the issue and it seems to be a problem with the schematics in nrwl. The process fails at the function `addNxModule` of `@nrwl\schematics\src\collection\application\index.js` at the line `25`.

I'm not sure if the issue is rooted in Xplat or Nrwl as I'm not quite sure how schematics work. Otherwise I'd like to help as much as a I can.

Here are the dependencies on the generated `package.json` following the instructions:

```
"dependencies": {
    "@angular/animations": "^6.1.0",
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "@ngrx/effects": "6.0.1",
    "@ngrx/router-store": "6.0.1",
    "@ngrx/store": "6.0.1",
    "@nrwl/nx": "6.2.0",
    "core-js": "^2.5.4",
    "rxjs": "^6.0.0",
    "zone.js": "^0.8.26",
    "@ngx-translate/core": "~10.0.1",
    "@ngx-translate/http-loader": "~3.0.1",
    "@CloudReports/scss": "file:libs/scss",
    "nativescript-angular": "~6.1.0",
    "nativescript-ngx-fonticon": "^4.2.0",
    "nativescript-theme-core": "^1.0.4",
    "reflect-metadata": "^0.1.12",
    "rxjs-compat": "^6.2.2",
    "tns-core-modules": "~4.2.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.1",
    "@angular/cli": "~6.1.2",
    "@angular/compiler-cli": "^6.1.0",
    "@angular/language-service": "^6.1.0",
    "@ngrx/store-devtools": "6.0.1",
    "@nrwl/schematics": "6.2.0",
    "@nstudio/schematics": "^6.2.3",
    "@types/jasmine": "~2.8.6",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.2.1",
    "jasmine-core": "~2.99.1",
    "jasmine-marbles": "0.3.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~1.4.2",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ngrx-store-freeze": "0.2.4",
    "prettier": "1.13.7",
    "protractor": "~5.3.0",
    "ts-node": "~5.0.1",
    "tslint": "~5.9.1",
    "typescript": "2.7.2",
    "tns-platform-declarations": "~4.2.0"
  },
  "xplat": {
    "prefix": "app"
  }
```

**Comment by NathanWalker** [comment]
Hi @neryortez thanks for this report. It might be your globally installed version on Nx.
I just tried your above steps and works here. Try this:
```
npm i -g @nrwl/schematics
```
Which should install latest version `6.2.0` and then try `create-nx-workspace name` again. Even though the package shows 6.2.0 it's possible that the globally installed version is older?

**Comment by NathanWalker** [comment]
I also am using:
```
Nathans-MacBook-Pro:companytestmonday nathan$ node -v
v10.2.1
Nathans-MacBook-Pro:companytestmonday nathan$ npm -v
6.1.0
```
Could be related to node but sounds like something with your global nrwl/schematic install potentially.

**Comment by neryortez** [comment]
It wasn't a nrwl/schematic problem. It was just after I updated node and npm, erased `node_modules` and ran `npm install` that it worked OK.

Thanks.

**Comment by NathanWalker** [comment]
Excellent great to hear!
