### ISSUE TITLE
Ionic performance

### ISSUE THREAD

**Issue by avantgarde0707** [nstudio/xplat#231]
Hi,

when I create new ionic application (nx + xplat based) and run it on device, it take a longer to start then ionic starter app. 

xplat -> 3 sec.
ionic starter app -> less than 1 sec.

Both are capacitor apps and includes only basics modules + splash screen.
Is there a way to speed up starting process used with xplat?

**Comment by NathanWalker** [comment]
@avantgarde0707 I wonder if related to Angular 11 perhaps? We just published xplat 11 however still working on a migration for existing workspaces and probably have a few additional things to do with Ionic and Angular 11.

Final touches are being made in this pr: https://github.com/nstudio/xplat/pull/232

**Comment by avantgarde0707** [comment]
Hi,

just tried to setup new repo with instruction from pr: #232 (to reproduce #231)
npx create-nx-workspace@latest
npm i @nstudio/xplat (11.0.3)
nx g app

results into:
? What name would you like for this app? temp2
? What type of app would like to create? ionic           [Ionic app]
? Would you like to configure routing for this app? No
√ Packages installed successfully.
- Installing packages (npm)...npm ERR! code ENOLOCAL
npm ERR! Could not install from "xplat\web\scss" as it does not contain a package.json file.
× Package install failed, see above.
Error: Workflow did not execute successfully.      

I'm missing something?

**Comment by NathanWalker** [comment]
Resolved with latest 11.0.21
