### ISSUE TITLE
Error nx serve <Project>: nx 12.3.6, Angular 12 Cannot find module 'webpack'

### ISSUE THREAD

**Issue by ghuarcayam** [nstudio/xplat#270]
I have created a new workspace and added a test application web-angular

I have an issue when generete execute project

![image](https://user-images.githubusercontent.com/25235099/121844101-0deb5d00-cca9-11eb-98b2-3110c7dfd9e3.png)

npx --version 
7.17.0

Angular 12

**Comment by NathanWalker** [comment]
Hi @ghuarcayam angular 12 support with xplat will be released this week as it’s in progress but in meantime you see this comment on how to create a workspace in meantime:
https://github.com/nstudio/xplat/issues/266#issuecomment-844642042

**Comment by iameduardod** [comment]
any update on xplat compatibility? @NathanWalker

**Comment by NathanWalker** [comment]
Hi @iameduardod yes planning on Thursday, sorry for delay, just got back from scheduled vacation last week.
