### ISSUE TITLE
Updates to Support Ionic in 4.0.0-beta.3

### ISSUE THREAD

**Issue by innovateworld** [nstudio/xplat#29]
I ran into a series of issues with Ionic and solved them one by one. Here are the needed changes in order for the Ionic 4.0.0-beta.3  and greater to work.

1. After running `npm run clean.ionic.[appName]` I would run into errors saying `rxjs-compat does not have a config file`. The solution:
> npm i rxjs-compat

2. After running `npm run start.ionic.[appName]` I would receive `[ng] ERROR in ../../node_modules/@ionic/core/dist/types/interface.d.ts(41,42): error TS1005: ';' expected.`. The solution was to update TypeScript in `package.json`:

> "typescript": "~2.9.2" 

3. After running `npm run start.ionic.[appName]` again the following error came up `[ng] ERROR in src/app/app.component.ts(3,10): error TS2305: Module '"/usr/app/node_modules/@ionic/core/dist/types/interface"' has no exported member 'isCapacitorNative'.`. The solution is to do the following in the Ionic Apps `app.component.ts` file.

A. Remove `import { isCapacitorNative } from '@ionic/core';`
B. Change ` if (isCapacitorNative(window))` to `if (this.platform.is('capacitor'))`

**Comment by NathanWalker** [comment]
Fixed in `6.2.7` now 👍
