### ISSUE TITLE
unable to generate new app after i have first generated an app

### ISSUE THREAD

**Issue by debuggerpk** [nstudio/xplat#30]
after i have generated my native script app doing

```bash
ng g app.nativescript reaction
```

i am unable to do

```bash
ng g app reaction
```

the system takes up 100% and the system does not go anywhere. I have tried with a blank repo, no avail.

**Comment by NathanWalker** [comment]
Hi @ysfjwd could you possibly provide the setup steps you took from the point of creating your Nx workspace from scratch?

**Comment by ysfjwd** [comment]
hi @NathanWalker ,I was able to solve the problem. My global `@nrwl/schematics` version was at `6.3.0`. Going through previous issues, you had mentioned that global schematics were not playing well, and you had advised to upgrade. Taking a guess in the wild, i downgraded my global schematics to `6.2.0` and it was able to generate.

As per the steps followed, they were as documented.

```bash
create-nx-workspace reaction --yarn
cd reaction
yarn install
yarn add @nstudio/schematics --dev
ng g app.nativescript reaction
```

it was fine uptil this point. The next point i.e. `ng g app reaction` was giving me a problem. For me, version matching `@nrwl/schematics` to `6.2.0` solved the issue.

**Comment by NathanWalker** [comment]
Good to hear thanks for reporting this. I’ll take a look with latest nrwl/schematics soon.
