### ISSUE TITLE
NativeScript core themes not applied

### ISSUE THREAD

**Issue by LeoDupont** [nstudio/xplat#32]
Hi !

I tried to apply the NativeScript core themes (doc : https://docs.nativescript.org/angular/ui/theme), in a NativeScript app within my xplat workspace, but it seems that themes are ignored (testing on Android).

By default, the `~nativescript-theme-core/css/core.light.css` theme appears to be applied without needing to import it. But when I import either `~nativescript-theme-core/css/core.dark.css` or a color palette like `~nativescript-theme-core/css/lime.css` into my app's `scss/_index.scss` file, no change is visible on my buttons or ActionBar.

Here is my `scss/_index.scss` file:
```
@import '~nativescript-theme-core/css/lime.css';
@import 'variables';
```

And here is the template of the first component to be loaded inside AppComponent's `<page-router-outlet>`:
```
<ActionBar class="action-bar" title="This is the title"></ActionBar>

<StackLayout class="page">
	<Label text="My first page" class="body"></Label>
	<Button class="btn btn-primary btn-active" text="Little button"></Button>
</StackLayout>
```

How can I use NativeScript core themes, color palettes or custom themes in an xplat workspace?

**Comment by NathanWalker** [comment]
Hi @LeoDupont core themes are in out of the box. Try importing your theme in here in the core shared code:
`xplat/nativescript/_common.scss`

**Comment by LeoDupont** [comment]
Hi @NathanWalker 

Thanks!

I can import either prebuilt themes or my custom themes in `xplat/nativescript/scss/_common.scss` (commenting out all the "{N} core theme rulesets") and it works 👍
