### ISSUE TITLE
{N} 5 and HMR

### ISSUE THREAD

**Issue by vance** [nstudio/xplat#44]
Just curious what patterns, especially build/run script setup will be put in place to handle HMR in {N} 5. Would the current xplat project setup even be affected? I haven't tried HMR with the xplat-ionic yet, but assume that works.

**Comment by NathanWalker** [comment]
HMR via {N} 5 will be provided via an ng update here when 5.0 is officially released and we have verified it doesn't cause any issues.

Not sure on HMR on Ionic.

**Comment by Dutchboy** [comment]
Any plans on checking version 5?

**Comment by NathanWalker** [comment]
@Dutchboy Yessir. Planning on this in next couple days. We wanted to make sure we're able to seamlessly add HMR into people's workspaces without issue as well as confirming {N} 5.0 is ready and compatible with the workspace.

**Comment by NathanWalker** [comment]
Holding off releasing {N} 5.0 compatibility as it's broken on iOS at moment due to [this](https://github.com/NativeScript/nativescript-angular/issues/1599). Once that's cleared things will be ready.

**Comment by NathanWalker** [comment]
`7.0.0` released now with {N} 5.0 compatibility:

https://twitter.com/wwwalkerrun/status/1062611645967433728
