### ISSUE TITLE
format is not applied to all files under xplat

### ISSUE THREAD

**Issue by m-abs** [nstudio/xplat#5]
Hi @NathanWalker 

`npm run format` only works for a few the files under `xplat/`.

e.g.:
```bash
xplat/nativescript/index.ts 3ms
xplat/web/index.ts 1ms
```

It is caused by the patch in: https://github.com/nstudio/xplat/blob/master/scripts/postinstall.ts#L34
The globs should be wrapped in quotation.

If I've time later tonight I'll write a PR fixing it.
But before I do that I've a question:
If I just fix the patch, it will throw an error, if the old-patch have been applied.

Do you want me to fix old already applied patch, or should I just let it throw that error?

**Comment by NathanWalker** [comment]
If possible to fix already applied patch would be preferable 🙏
