### ISSUE TITLE
suggestion to organize schematics

### ISSUE THREAD

**Issue by galki** [nstudio/xplat#53]
this is regrding https://github.com/nrwl/nx/issues/619#issuecomment-440356808

i love what xplat makes possible but i find it difficult to use because of its opinionated nature. to make my point of view clear, i see that xplat is about extending nx with the ability to create nativescript, ionic, electron, etc apps in addition to what nx already has, angular "web" apps. however, xplat goes beyond this by populating the libs directory and any generated app dirs with opinionated base code.

### problem
the generated opinionated base code conflicts with my opinionated base code.

### suggested solution
split the schematics into core (`ng g app` commands) and optional (everything else including the `xplat` dir).

on one hand there shouldn't even be optional schematics because people could extend the core collection with their own schematic repos. on the other hand if enough standards exist having "official" optional schematics that could all be run separately (i.e. one for i18n, one for themes, etc) would be helpful too.

**Comment by NathanWalker** [comment]
Great insight and thank you for starting this discussion. I’m going to give some thought to this as well as I like your suggestions and hopefully can resolve down on something that works well for your use case while maintaining the other as well.

**Comment by galki** [comment]
@NathanWalker i appreciate it. im all in favor of effort being concentrated and fruitful. let me know if you need help down the road.

**Comment by galki** [comment]
@NathanWalker congrats and thanks! i've had my eyes off of ionic for a bit but i'll take a look at the new schematics.
