### ISSUE TITLE
Error in "npm i"

### ISSUE THREAD

**Issue by Stronhold** [nstudio/xplat#57]
### Reproduction
```
create-nx-workspace demo
cd .\demo\
 npm install @nstudio/schematics --save-dev
ng g xplat --prefix=foo --platforms=web,electron
ng g app web
ng g app.electron desktop --target=web-web
npm i

```
### Output

```
"ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES" is not recognized as an internal or external command, operable program or batch file. 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo@0.0.0 postinstall: `ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true npx electron-builder install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the demo@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
OS: Windows 10
npm: 6.4.1
node: 10.4.1

**Comment by NathanWalker** [comment]
Thanks for this report, will investigate on windows here 👍

**Comment by dmitryr117** [comment]
On Windows for now in the root package.json file i changed line 31 to:
"postinstall": "set ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true npx electron-builder install-app-deps",

**Comment by dmitryr117** [comment]
I did and it sort of worked. I think a screen for electron setup appeared though. It was over a week ago now. Can't remember exactly what happened. Interesting thing. Even though this env variable error was showing on `npm i` without modification of package.json  - electron project would still work when running `npm run start.electron.appname`

**Comment by madmath03** [comment]
Encountered the same error on Windows 10 from a fresh new app.
Changing postinstall to `set ...` as mentioned by @dmitryr117 worked for me but if I remove completely the variable, the electron install fails : 
```
> ngxp@0.0.0 postinstall D:\dev\text-xplat\ngxp
> npx electron-builder install-app-deps

  • electron-builder version=20.28.4
Error: Unresolved node modules: @angular/http
    at D:\dev\text-xplat\ngxp\node_modules\app-builder-lib\src\util\packageDependencies.ts:108:17
From previous event:
...
```

**Comment by NathanWalker** [comment]
In `7.3.1` I ended up ensuring `@angular/http` is at least installed to avoid the need of using `ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES` keeping things simpler.

You can now run `ng update @nstudio/schematics` if using angular cli `7.3.x` and above. If using previous version just note [this here](https://github.com/nstudio/xplat/wiki/Use-ng-update) if using `ng update` 👍
