### ISSUE TITLE
Routing not working in the Ionic App

### ISSUE THREAD

**Issue by skpulipaka26** [nstudio/xplat#60]
Routing is not working in the ionic 4 app created. 
The URL is updated, but the view is not rendered.

**Comment by NathanWalker** [comment]
Thanks for reporting @skpulipaka26 - we are working on updating the Ionic generator to use the new schematics from the Ionic team which will solve this.

**Comment by skpulipaka26** [comment]
Thank you very much @NathanWalker

**Comment by NathanWalker** [comment]
This has been fixed in latest as it’d using official v4 release now.
