### ISSUE TITLE
Bug: Generators for directives, pipes and services uses inconsistent array names

### ISSUE THREAD

**Issue by m-abs** [nstudio/xplat#68]
Hi,

If I have a feature named `hugo` without any directives and create a new directive:
```bash
 > ng g directive first --feature hugo
CREATE libs/features/hugo/directives/first.directive.ts (138 bytes)
CREATE libs/features/hugo/directives/index.ts (103 bytes)
UPDATE libs/features/hugo/hugo.module.ts (252 bytes)
```

`libs/features/hugo/directives/index.ts` looks like this:
```typescript
import { FirstDirective } from './first.directive';

export const FIRST_DIRECTIVES = [FirstDirective];
```

`libs/features/hugo/hugo.module.ts` looks like this
```typescript
import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { HUGO_DIRECTIVES } from './directives';

@NgModule({
  schemas: [NO_ERRORS_SCHEMA],
  declarations: [...HUGO_DIRECTIVES],
  exports: [...HUGO_DIRECTIVES]
})
export class HugoModule {}
```

As you can see `FIRST_DIRECTIVES` is exported but the `HugoModule` expects the name  `HUGO_DIRECTIVES`.

This is only a problem when the `directives/index.ts`-file doesn't exists.

It is the same issue with `services` and `pipes`.

I'm making a PR fixing this in a moment.

**Comment by eng-ahmedsaleh** [comment]
I still have an issue while generating pipe or directive.

example: generate pipe to the default feature (UI) 

`ng generate @nstudio/schematics:pipe size`

> CREATE libs/features/ui/pipes/size.pipe.ts (183 bytes)
> UPDATE libs/features/ui/pipes/index.ts (476 bytes)
> UPDATE libs/features/ui/ui.module.ts (362 bytes)


**libs/features/ui/pipes/index.js**    this exports a _PIPES_ array.
```
export const PIPES = [
  DateOrderPipe,
  SizePipe
];
```

**libs/features/ui/ui.module.ts**      imports _UI_PIPES_ array which is not found (not exported)
`import { UI_PIPES } from './pipes';`

The same thing applied with directives
