### ISSUE TITLE
ionic problems

### ISSUE THREAD

**Issue by OctAg0nO** [nstudio/xplat#7]
[ts] Cannot find module '@myWorkspace/ionic'.

Failed to compile.
global.scss
@import '~@myWorkspace/ionic/scss/index';

ng update
Not found : @myWorkspace/scss

ionic  4.0.0-rc.11
Angular CLI: 6.0.8
Node: 10.7.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.2
typescript                   2.7.2

**Comment by NathanWalker** [comment]
Hi @OctAg0nO this is issue with angular cli and `ng update` actually:
https://github.com/angular/angular-cli/issues/10614

The solution is to temporarily remove any `file:` ref dependencies in package, run `ng update` then add them back. Hopefully that will be fixed soon.

**Comment by OctAg0nO** [comment]
Hi @NathanWalker

im having some other problems in ionic generated app...

1 - importing @myWorkspace/* return **[ts] Cannot find module '@myWorkspace/ionic'.**
errors remove importing full path ../../../../

2 - running **npm run start.ionic.appname**  get compile error.
can compile removing @import '~@myWorkspace/ionic/scss/index'; from global scss

**Comment by NathanWalker** [comment]
Did you try running `npm i` in the root of your workspace?
I'll look into this in moment but lemme know if that changes things for you. Also can you drop your `angular.json` here? Would be curious to see if for some reason your setup is different in anyway than expected.

**Comment by OctAg0nO** [comment]
yes, i run npm i
the problem is only in the ionic generated app...    web and nativescript works fine..

in the ionic app angular.json i get this error

Unable to load schema from 'c:\testApp\user\apps\ionic-testing\node_modules\@angular-devkit\core\src\workspace\workspace-schema.json':


here  in the angular.json from the ionic generated app

{
  "$schema": "./node_modules/@angular-devkit/core/src/workspace/workspace-schema.json",
  "version": 1,
  "projects": {
    "app": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "rg",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "progress": false,
            "outputPath": "www",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [{
                "glob": "**/*",
                "input": "src/assets",
                "output": "assets"
              },
              {
                "glob": "**/*.svg",
                "input": "node_modules/@ionic/angular/dist/ionic/svg",
                "output": "./svg"
              }
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "node_modules"
              ]
            },
            "styles": [
              {
                "input": "src/theme/variables.scss"
              },
              {
                  "input": "src/global.scss"
              }
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [{
                "replace": "src/environments/environment.ts",
                "with": "src/environments/environment.prod.ts"
              }],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "app:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "app:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "styles.css"
            ],
            "scripts": [],
            "assets": [{
                "glob": "favicon.ico",
                "input": "src/",
                "output": "/"
              },
              {
                "glob": "**/*",
                "input": "src/assets",
                "output": "/assets"
              }
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "app"
}

**Comment by NathanWalker** [comment]
Ok yeah sounds like `@angular-devkit\core` dep is missing for some reason on your setup. You may try installing that in root of workspace or directly in Ionic app. I'll also look into things on this end for next update as I was planning on rolling out updates in next couple days for Angular 6.1, etc.

**Comment by OctAg0nO** [comment]
ok.
problem is solved running **npm i** inside my ionic app  root directory too

**Comment by NathanWalker** [comment]
ah here's another thing you can do in future:
`npm run clean.ionic.appname` which is always handy to just clean the app and reinstall it's deps which should have same net effect 👍

**Comment by OctAg0nO** [comment]
@NathanWalker, thanx for your help .. 👍👍👍 :)

**Comment by OctAg0nO** [comment]
hey @NathanWalker runing **npm i**  or **npm run clean.ionic.appname** solve all the imports problem exept for one, in the ionic app home.component.ts still getting this error

**[ts] Cannot find module '@myWorkspace/core'.**

the problem is only importing the /core module now

**Comment by NathanWalker** [comment]
What command are you using to run your Ionic app?

**Comment by OctAg0nO** [comment]
the application is  working, i can run the application with **npm run start.ionic.appname**
, im getting the error in vscode..

**Comment by NathanWalker** [comment]
Ah ok gotcha. Could be your VSCode settings - guess I'd have to see where in VSCode you see that - I assume as a red squiggly and hover? If so that's just VSCode taking a bit to index usually. Often if you quit VSCode and relaunch later it can awaken it 👍

**Comment by OctAg0nO** [comment]
error is in the myWorkspace/apps/ionic-myApp/home.component.ts

import { BaseComponent } from '@myWorkspace/core';

on hover says 
**[ts] Cannot find module '@myWorkspace/core'.**

**Comment by OctAg0nO** [comment]
relaunch the vscode
remove node_modules in my workspace root dir , and ionic root dir
**npm cache clean -f** 
**npm i** in my workspace root dir , and ionic root dir

error still there

error is in the myWorkspace/apps/ionic-myApp/home.component.ts

import { BaseComponent } from '@myWorkspace/core';

on hover says
[ts] Cannot find module '@myWorkspace/core'.

im going to check my vsconfig and let you know..
