### ISSUE TITLE
ng update fails with 404 on /scss directory

### ISSUE THREAD

**Issue by vance** [nstudio/xplat#71]
Having trouble updating from schematics 6.3.2 to latest (7.2.1 currently). 

```
ng update @nstudio/schematics
404 Not Found: @projectname/scss
```

however, this directory exists under `libs/` and hasn't even been touched since the project was generated.

<img width="252" alt="image" src="https://user-images.githubusercontent.com/145471/50849474-02ebb000-132c-11e9-812c-85b648ebe69d.png">

**Comment by m-abs** [comment]
It's a bug in the angular cli.
You've to temporarily remove the modules from the package.json, run the update and add the module again.

**Comment by NathanWalker** [comment]
It’s true although word is the latest angular cli may have fixed it. In meantime see this note:
https://github.com/nstudio/xplat/wiki/Use-ng-update

**Comment by vance** [comment]
sorry, remove which modules from which package.json? Remove node-sass? Or do you mean the file reference to `"@projectname/scss": "file:../../libs/scss",` in each project?

**Comment by vance** [comment]
ah, ok, thanks for that link.
