### ISSUE TITLE
Ionic: The request of a dependency is an expression

### ISSUE THREAD

**Issue by jurienhamaker** [nstudio/xplat#76]
Hello,

I tried to create a xplat environment using the following commands from your documentation;

    npm install -g @nrwl/schematics
    npm install -g @angular/cli
    create-nx-workspace test-xplat

    npm install @nstudio/schematics --save-dev

    ng g xplat --prefix=test --platforms=web,ionic

    ng g app test
    ng g app.ionic test

    npm run start.ionic.test

I am then greeted with the following errors and no working ionic application;

    [ng] WARNING in /opt/app/node_modules/@angular/core/fesm5/core.js
    [ng] 18261:15-36 Critical dependency: the request of a dependency is an expression
    [ng] WARNING in /opt/app/node_modules/@angular/core/fesm5/core.js
    [ng] 18273:15-102 Critical dependency: the request of a dependency is an expression

Any idea how this can come up ? I tried removing all dependencies etc (links to the xplat env & libs).

**Comment by NathanWalker** [comment]
@KingsDevelopment when you can please run `ng --version` and post your results here.
I believe this is caused by an older version of @angular/schematics installed.

**Comment by NathanWalker** [comment]
<img width="419" alt="screen shot 2019-01-25 at 9 49 19 am" src="https://user-images.githubusercontent.com/457187/51763116-888a9200-2086-11e9-90bc-a41db172478d.png">

**Comment by KingsDevelopment** [comment]
I tried redoing the steps I mentioned, but I am getting the following few errors here and there;

    [error] xplat/ionic/core/core.module.ts: SyntaxError: ';' expected. (4:45)
    [error]   2 | 
    [error]   3 | import { IonicModule } from '@ionic/angular';
    [error] > 4 | import { throwIfAlreadyLoaded } from '@test'/utils';
    [error]     |                                             ^
    [error]   5 | import { TestCoreModule } from '@test'/web';
    [error]   6 | 
    [error]   7 | @NgModule({

there are a lot of them when running `ng g xplat --prefix=test --platforms=web,ionic`

**Comment by KingsDevelopment** [comment]
besides those errors, this is my `ng --version` output:

    Angular CLI: 7.2.3
    Node: 11.7.0
    OS: linux x64
    Angular: 7.2.2
    ... animations, common, compiler, compiler-cli, core, forms
    ... language-service, platform-browser, platform-browser-dynamic
    ... router

    Package                           Version
    -----------------------------------------------------------
    @angular-devkit/architect         0.11.4
    @angular-devkit/build-angular     0.11.4
    @angular-devkit/build-optimizer   0.11.4
    @angular-devkit/build-webpack     0.11.4
    @angular-devkit/core              7.1.4
    @angular-devkit/schematics        7.2.3
    @angular/cli                      7.2.3
    @ngtools/webpack                  7.1.4
    @schematics/angular               7.2.3
    @schematics/update                0.12.3
    rxjs                              6.3.3
    typescript                        3.2.4
    webpack                           4.23.1

**Comment by NathanWalker** [comment]
What node and npm versions?
Also I assume you’re on a Mac? (I think that’s what it looked like in your orig desc?)

**Comment by KingsDevelopment** [comment]
@NathanWalker I run everything in docker. And usually by yarn. but I had the same errors with npm.

So for your understanding:

I am using the `node:11` docker. Which results in node version `v11.7.0` with npm version `6.5.0`

Here are my outputs:

`npm install -g @nrwl/schematics @angular/cli ionic`:

	/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng
	/usr/local/bin/create-nx-workspace -> /usr/local/lib/node_modules/@nrwl/schematics/bin/create-nx-workspace.js
	/usr/local/bin/nx -> /usr/local/lib/node_modules/@nrwl/schematics/src/command-line/nx.js
	/usr/local/bin/ionic -> /usr/local/lib/node_modules/ionic/bin/ionic
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@angular/cli/node_modules/fsevents):
	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {
		"os": "darwin",
		"arch": "any"
	} (current: {
		"os": "linux",
		"arch": "x64"
	})

	+ @angular/cli@7.2.3
	+ ionic@4.9.0
	+ @nrwl/schematics@7.5.0
	added 682 packages from 305 contributors in 18.404s


`create-nx-workspace newtest`:

	Creating a sandbox with the CLI and Nx Schematics...
	added 383 packages from 224 contributors and audited 16340 packages in 5.516s
	found 0 vulnerabilities

	ng new "newtest" --collection=@nrwl/schematics 
	? Which stylesheet format would you like to use? SCSS   [ http: //sass-lang.com   ]
	? What is the npm scope you would like to use for your Nx Workspace? newtest
	? Which Package Manager would you like to use for your workspace? npm
	CREATE newtest/.prettierignore (57 bytes)
	CREATE newtest/.prettierrc (25 bytes)
	CREATE newtest/README.md (1859 bytes)
	CREATE newtest/.editorconfig (245 bytes)
	CREATE newtest/.gitignore (503 bytes)
	CREATE newtest/angular.json (459 bytes)
	CREATE newtest/karma.conf.js (1012 bytes)
	CREATE newtest/nx.json (198 bytes)
	CREATE newtest/package.json (2519 bytes)
	CREATE newtest/tsconfig.json (427 bytes)
	CREATE newtest/tslint.json (2307 bytes)
	CREATE newtest/apps/.gitkeep (1 bytes)
	CREATE newtest/libs/.gitkeep (0 bytes)
	CREATE newtest/tools/tsconfig.tools.json (254 bytes)
	CREATE newtest/tools/schematics/.gitkeep (0 bytes)
	npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.

	> node-sass@4.10.0 install /opt/newtest/node_modules/node-sass
	> node scripts/install.js

	Downloading binary from https: //github.com/sass/node-sass/releases/download/v4.10.0/linux-x64-67_binding.node
	Download complete..
	] - :
	Binary saved to /opt/newtest/node_modules/node-sass/vendor/linux-x64-67/binding.node
	Caching binary to /root/.npm/node-sass/4.10.0/linux-x64-67_binding.node

	> node-sass@4.10.0 postinstall /opt/newtest/node_modules/node-sass
	> node scripts/build.js

	Binary found at /opt/newtest/node_modules/node-sass/vendor/linux-x64-67/binding.node
	Testing binary
	Binary is fine
	npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
	npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
	npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/router@^6.0.0 but none is installed. You must install peer dependencies yourself.
	npm WARN @ngrx/store@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
	npm WARN @ngrx/effects@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
	npm WARN @ngtools/webpack@7.1.4 requires a peer of typescript@>=2.4.0 < 3.2 but none is installed. You must install peer dependencies yourself.
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {
		"os": "darwin",
		"arch": "any"
	} (current: {
		"os": "linux",
		"arch": "x64"
	})

	added 1206 packages from 1198 contributors and audited 40346 packages in 23.012s
	found 1 high severity vulnerability
	run `npm audit fix` to fix them, or `npm audit` for details

`npm i @nstudio/schematics -D`:

    > @nstudio/schematics@7.2.6 postinstall /opt/newtest/node_modules/@nstudio/schematics
    > [ ! -f scripts/postinstall.js ] || node scripts/postinstall.js

    Patch for nx format have been applied
    "/opt/newtest/node_modules/.prettierignore" already exists
    npm WARN @ngrx/effects@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN @ngrx/router-store@6.1.2 requires a peer of @angular/router@^6.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN @ngrx/store@6.1.2 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
    npm WARN @ngtools/webpack@7.1.4 requires a peer of typescript@>=2.4.0 < 3.2 but none is installed. You must install peer dependencies yourself.
    npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
    npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

    + @nstudio/schematics@7.2.6
    added 1 package from 8 contributors and audited 40350 packages in 7.975s
    found 1 high severity vulnerability
    run `npm audit fix` to fix them, or `npm audit` for details

`ng g xplat --prefix=foo --platforms=ionic,web`: (Used foo because test error'd out before)

    ng g xplat --prefix=foo --platforms=ionic,web
    CREATE references.d.ts (158 bytes)
    CREATE libs/core/core.module.ts (1365 bytes)
    CREATE libs/core/index.ts (164 bytes)
    CREATE libs/core/base/base-component.ts (579 bytes)
    CREATE libs/core/base/index.ts (34 bytes)
    CREATE libs/core/environments/environment.ts (110 bytes)
    CREATE libs/core/models/index.ts (42 bytes)
    CREATE libs/core/models/xplat-window.interface.ts (638 bytes)
    CREATE libs/core/services/index.ts (260 bytes)
    CREATE libs/core/services/log.service.spec.ts (4558 bytes)
    CREATE libs/core/services/log.service.ts (1300 bytes)
    CREATE libs/core/services/tokens.ts (405 bytes)
    CREATE libs/core/services/window.service.ts (1995 bytes)
    CREATE libs/features/index.ts (21 bytes)
    CREATE libs/features/ui/index.ts (68 bytes)
    CREATE libs/features/ui/ui.module.ts (332 bytes)
    CREATE libs/features/ui/base/header.base-component.ts (466 bytes)
    CREATE libs/features/ui/base/index.ts (41 bytes)
    CREATE libs/features/ui/pipes/date-order.pipe.ts (563 bytes)
    CREATE libs/features/ui/pipes/index.ts (93 bytes)
    CREATE libs/scss/_index.scss (166 bytes)
    CREATE libs/scss/_variables.scss (218 bytes)
    CREATE libs/scss/package.json (52 bytes)
    CREATE libs/utils/angular.ts (213 bytes)
    CREATE libs/utils/index.ts (82 bytes)
    CREATE libs/utils/objects.ts (172 bytes)
    CREATE libs/utils/platform.ts (699 bytes)
    CREATE xplat/web/index.ts (52 bytes)
    CREATE xplat/web/package.json (97 bytes)
    CREATE xplat/web/core/core.module.spec.ts (171 bytes)
    CREATE xplat/web/core/core.module.ts (1547 bytes)
    CREATE xplat/web/core/index.ts (69 bytes)
    CREATE xplat/web/core/base/app.base-component.ts (257 bytes)
    CREATE xplat/web/core/base/index.ts (38 bytes)
    CREATE xplat/web/features/index.ts (21 bytes)
    CREATE xplat/web/features/ui/index.ts (38 bytes)
    CREATE xplat/web/features/ui/ui.module.spec.ts (150 bytes)
    CREATE xplat/web/features/ui/ui.module.ts (483 bytes)
    CREATE xplat/web/scss/_index.scss (297 bytes)
    CREATE xplat/web/scss/_spacing.scss (2323 bytes)
    CREATE xplat/web/scss/_tags.scss (68 bytes)
    CREATE xplat/web/scss/_variables.scss (33 bytes)
    CREATE xplat/ionic/index.ts (52 bytes)
    CREATE xplat/ionic/package.json (99 bytes)
    CREATE xplat/ionic/core/core.module.ts (480 bytes)
    CREATE xplat/ionic/core/index.ts (52 bytes)
    CREATE xplat/ionic/features/index.ts (21 bytes)
    CREATE xplat/ionic/features/ui/index.ts (70 bytes)
    CREATE xplat/ionic/features/ui/ui.module.ts (477 bytes)
    CREATE xplat/ionic/features/ui/components/index.ts (116 bytes)
    CREATE xplat/ionic/features/ui/components/header/header.component.html (116 bytes)
    CREATE xplat/ionic/features/ui/components/header/header.component.ts (249 bytes)
    CREATE xplat/ionic/scss/_index.scss (612 bytes)
    CREATE xplat/ionic/scss/_tags.scss (123 bytes)
    CREATE testing/karma.conf.js (965 bytes)
    CREATE testing/test.libs.ts (617 bytes)
    CREATE testing/test.xplat.ts (357 bytes)
    CREATE testing/tsconfig.libs.json (836 bytes)
    CREATE testing/tsconfig.libs.spec.json (296 bytes)
    CREATE testing/tsconfig.xplat.json (166 bytes)
    CREATE testing/tsconfig.xplat.spec.json (284 bytes)
    UPDATE .gitignore (788 bytes)
    UPDATE angular.json (1999 bytes)
    UPDATE nx.json (276 bytes)
    UPDATE tslint.json (2335 bytes)
    UPDATE tsconfig.json (766 bytes)
    UPDATE package.json (3066 bytes)

    > newtest@0.0.0 format /opt/newtest
    > nx format:write "--untracked" "--quiet"

Left out the formatting, cause it runs fine and only adds more log.

`ng g app bar`:

    ? In which directory should the application be generated? 
    ? Would you like to add Angular routing? Yes
    ? Which stylesheet format would you like to use? SCSS   [ http://sass-lang.com   ]
    ? Which Unit Test Runner would you like to use for the application? Karma [ https://karma-runner.github.io ]
    ? Which E2E Test Runner would you like to use for the application? Protractor [ https://www.protractortest.org ]
    ? Which tags would you like to add to the application? (used for linting) web
    CREATE apps/web-bar/tsconfig.json (118 bytes)
    CREATE apps/web-bar-e2e/tsconfig.json (132 bytes)
    CREATE apps/web-bar-e2e/protractor.conf.js (757 bytes)
    CREATE apps/web-bar-e2e/tsconfig.e2e.json (210 bytes)
    CREATE apps/web-bar-e2e/src/app.e2e-spec.ts (655 bytes)
    CREATE apps/web-bar-e2e/src/app.po.ts (239 bytes)
    CREATE apps/web-bar/browserslist (388 bytes)
    CREATE apps/web-bar/karma.conf.js (484 bytes)
    CREATE apps/web-bar/tsconfig.app.json (196 bytes)
    CREATE apps/web-bar/tsconfig.spec.json (237 bytes)
    CREATE apps/web-bar/tslint.json (187 bytes)
    CREATE apps/web-bar/src/favicon.ico (5430 bytes)
    CREATE apps/web-bar/src/index.html (309 bytes)
    CREATE apps/web-bar/src/main.ts (376 bytes)
    CREATE apps/web-bar/src/polyfills.ts (3569 bytes)
    CREATE apps/web-bar/src/test.ts (642 bytes)
    CREATE apps/web-bar/src/styles.scss (21 bytes)
    CREATE apps/web-bar/src/assets/.gitkeep (0 bytes)
    CREATE apps/web-bar/src/environments/environment.prod.ts (51 bytes)
    CREATE apps/web-bar/src/environments/environment.ts (662 bytes)
    CREATE apps/web-bar/src/app/app.module.ts (510 bytes)
    CREATE apps/web-bar/src/app/app.component.scss (0 bytes)
    CREATE apps/web-bar/src/app/app.component.html (31 bytes)
    CREATE apps/web-bar/src/app/app.component.spec.ts (2254 bytes)
    CREATE apps/web-bar/src/app/app.component.ts (284 bytes)
    CREATE apps/web-bar/src/app/core/core.module.ts (168 bytes)
    CREATE apps/web-bar/src/app/features/shared/shared.module.ts (216 bytes)
    CREATE apps/web-bar/src/assets/nx-logo.png (71592 bytes)
    CREATE apps/web-bar/src/assets/xplat.png (12796 bytes)
    CREATE apps/web-bar/src/assets/i18n/en.json (30 bytes)
    CREATE apps/web-bar/src/scss/_index.scss (44 bytes)
    CREATE apps/web-bar/src/scss/_variables.scss (25 bytes)
    CREATE apps/web-bar/src/app/app.routing.ts (483 bytes)
    CREATE apps/web-bar/src/app/features/home/home.module.ts (475 bytes)
    CREATE apps/web-bar/src/app/features/home/components/home.component.html (822 bytes)
    CREATE apps/web-bar/src/app/features/home/components/home.component.ts (221 bytes)
    CREATE apps/web-bar/src/app/features/home/components/index.ts (138 bytes)
    UPDATE angular.json (6020 bytes)
    UPDATE package.json (3180 bytes)
    UPDATE nx.json (368 bytes)

    > newtest@0.0.0 format /opt/newtest
    > nx format:write "--untracked" "--quiet"

`ng g app.ionic bar`:

    CREATE apps/ionic-bar/angular.json (4934 bytes)
    CREATE apps/ionic-bar/capacitor.config.json (106 bytes)
    CREATE apps/ionic-bar/ionic.config.json (86 bytes)
    CREATE apps/ionic-bar/package.json (4018 bytes)
    CREATE apps/ionic-bar/tsconfig.json (408 bytes)
    CREATE apps/ionic-bar/tslint.json (2915 bytes)
    CREATE apps/ionic-bar/.gitignore (425 bytes)
    CREATE apps/ionic-bar/src/global.scss (740 bytes)
    CREATE apps/ionic-bar/src/index.html (686 bytes)
    CREATE apps/ionic-bar/src/karma.conf.js (965 bytes)
    CREATE apps/ionic-bar/src/main.ts (374 bytes)
    CREATE apps/ionic-bar/src/polyfills.ts (3709 bytes)
    CREATE apps/ionic-bar/src/test.ts (642 bytes)
    CREATE apps/ionic-bar/src/tsconfig.app.json (584 bytes)
    CREATE apps/ionic-bar/src/tsconfig.spec.json (693 bytes)
    CREATE apps/ionic-bar/src/app/app-routing.module.ts (402 bytes)
    CREATE apps/ionic-bar/src/app/app.component.html (63 bytes)
    CREATE apps/ionic-bar/src/app/app.component.ts (569 bytes)
    CREATE apps/ionic-bar/src/app/app.module.ts (638 bytes)
    CREATE apps/ionic-bar/src/app/core/core.module.ts (179 bytes)
    CREATE apps/ionic-bar/src/app/features/shared/shared.module.ts (239 bytes)
    CREATE apps/ionic-bar/src/app/pages/home/home-routing.module.ts (394 bytes)
    CREATE apps/ionic-bar/src/app/pages/home/home.component.html (429 bytes)
    CREATE apps/ionic-bar/src/app/pages/home/home.component.ts (227 bytes)
    CREATE apps/ionic-bar/src/app/pages/home/home.module.ts (423 bytes)
    CREATE apps/ionic-bar/src/assets/shapes.svg (1176 bytes)
    CREATE apps/ionic-bar/src/assets/i18n/en.json (28 bytes)
    CREATE apps/ionic-bar/src/assets/icon/favicon.ico (1981 bytes)
    CREATE apps/ionic-bar/src/assets/icon/favicon.png (930 bytes)
    CREATE apps/ionic-bar/src/assets/imgs/logo.png (39757 bytes)
    CREATE apps/ionic-bar/src/environments/environment.prod.ts (51 bytes)
    CREATE apps/ionic-bar/src/environments/environment.ts (662 bytes)
    CREATE apps/ionic-bar/src/theme/variables.scss (2434 bytes)
    UPDATE package.json (3988 bytes)
    UPDATE angular.json (6292 bytes)
    UPDATE nx.json (426 bytes)

    > newtest@0.0.0 format /opt/newtest
    > nx format:write "--untracked" "--quiet"

Before I could run `npm run start.ionic.bar` I had to first `npm i` in the root directory & the `apps/src/ionic-bar/` directory before I could do `npm run start.ionic.bar` without all kinds of errors.

`npm run start.ionic.bar`:

    > newtest@0.0.0 start.ionic.bar /opt/newtest
    > cd apps/ionic-bar && npm start


    > ionicbar@0.0.0 start /opt/newtest/apps/ionic-bar
    > ionic serve

    > ng run app:serve --host=0.0.0.0 --port=8100
    [ng] WARNING: This is a simple server for use in testing or debugging Angular applications
    [ng] locally. It hasn't been reviewed for security issues.
    [ng] Binding this server to an open connection can result in compromising your application or
    [ng] computer. Using a different host than the one passed to the "--host" flag might result in
    [ng] websocket connection issues. You might need to use "--disableHostCheck" if that's the
    [ng] case.

    [INFO] Development server running!
        
        Local: http://localhost:8100
        External: http://172.17.0.2:8100
        DevApp: exampleApp@8100 on 5ed595850434
        
        Use Ctrl+C to quit this process

    [INFO] Browser window opened to http://localhost:8100!

    [ng] Date: 2019-01-29T09:31:49.903Z
    [ng] Hash: 052466d87a74689b2a06
    [ng] Time: 3791ms
    [ng] chunk {main} main.js, main.js.map (main) 1.84 kB [initial] [rendered]
    [ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 92.3 kB [initial] [rendered]
    [ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 6.08 kB [entry] [rendered]
    [ng] chunk {styles} styles.js, styles.js.map (styles) 114 kB [initial] [rendered]
    [ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 327 kB [initial] [rendered]
    [ng] 
    [ng] ERROR in No NgModule metadata found for 'HomePageModule'.
    [ng] ℹ ｢wdm｣: Failed to compile.

After fixing the NgModule metadata:

line 6 on `app-routing.module.ts`:
`{ path: 'home', loadChildren: './pages/home/home.module#HomePageModule' }`

Change it to:
`{ path: 'home', loadChildren: './pages/home/home.module#HomeModule' }`


again `npm run start.ionic.bar`:

    > newtest@0.0.0 start.ionic.bar /opt/newtest
    > cd apps/ionic-bar && npm start


    > ionicbar@0.0.0 start /opt/newtest/apps/ionic-bar
    > ionic serve

    > ng run app:serve --host=0.0.0.0 --port=8100
    [ng] WARNING: This is a simple server for use in testing or debugging Angular applications
    [ng] locally. It hasn't been reviewed for security issues.
    [ng] Binding this server to an open connection can result in compromising your application or
    [ng] computer. Using a different host than the one passed to the "--host" flag might result in
    [ng] websocket connection issues. You might need to use "--disableHostCheck" if that's the
    [ng] case.

    [INFO] Development server running!
        
        Local: http://localhost:8100
        External: http://172.17.0.2:8100
        DevApp: exampleApp@8100 on 5ed595850434
        
        Use Ctrl+C to quit this process

    [INFO] Browser window opened to http://localhost:8100!

    [ng] Date: 2019-01-29T09:34:36.405Z
    [ng] Hash: 66c21b82143a8c152673
    [ng] Time: 11025ms
    [ng] chunk {common} common.js, common.js.map (common) 19.4 kB  [rendered]
    [ng] chunk {main} main.js, main.js.map (main) 104 kB [initial] [rendered]
    [ng] chunk {pages-home-home-module} pages-home-home-module.js, pages-home-home-module.js.map (pages-home-home-module) 8.08 kB  [rendered]
    [ng] chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 236 kB [initial] [rendered]
    [ng] chunk {runtime} runtime.js, runtime.js.map (runtime) 8.8 kB [entry] [rendered]
    [ng] chunk {styles} styles.js, styles.js.map (styles) 114 kB [initial] [rendered]
    [ng] chunk {vendor} vendor.js, vendor.js.map (vendor) 4.85 MB [initial] [rendered]
    [INFO] ... and 173 additional chunks
    [ng] ℹ ｢wdm｣: Compiled successfully.


Now runs succesfully.

I will try updating the current versions in my already existing xplat environment and see if it works there.
Will come back on this.

**Comment by KingsDevelopment** [comment]
On our own setup I am still getting errors. I might be able to give you access to the repository if you can pm me your email.

**Comment by NathanWalker** [comment]
Ok @KingsDevelopment this was very helpful. `7.2.7` published now contains the final fix (it was a naming issue on the Ionic home module).

If you did that flow again should run fine. Lemme know and we'll close this if so 👍

**Comment by NathanWalker** [comment]
Thanks and absolutely happy to help.

**Comment by vance** [comment]
We still get the "The request of a dependency is an expression " error. Additionally, none of the imported modules from `libs` or `xplat` work at all. It compiles, but always an injector error. Could these be related?

**Comment by NathanWalker** [comment]
@vance do you have a repo to share by chance? Can even email me a zip of it privately. Would love to take a look at the workspace and see if I can determine if something is there that may be causing this?
