### ISSUE TITLE
ng g ngrx - usage question

### ISSUE THREAD

**Issue by m-abs** [nstudio/xplat#8]
Hi,

I'm trying to generate a shared `@ngrx/store` under my `login`-feature.

First a minor problem, error message prints an incorrect example:
```bash
> ng g ngrx
You did not specify the name of the state you'd like to generate. For example: ng g state my-state --feature=foo --platforms=web,nativescript
```

- `ng g state` isn't a command
- The name`my-state` generated invalid code, it should to be camelCased

If I follow the advice (assuming it `store` should've been `ngrx`):
```bash
 > ng g ngrx session --feature=login --platforms=web,nativescript
CREATE xplat/nativescript/features/login/state/index.ts (90 bytes)
CREATE xplat/nativescript/features/login/state/session.actions.ts (662 bytes)
CREATE xplat/nativescript/features/login/state/session.effects.spec.ts (1017 bytes)
CREATE xplat/nativescript/features/login/state/session.effects.ts (714 bytes)
CREATE xplat/nativescript/features/login/state/session.reducer.spec.ts (401 bytes)
CREATE xplat/nativescript/features/login/state/session.reducer.ts (474 bytes)
CREATE xplat/nativescript/features/login/state/session.state.ts (219 bytes)
CREATE xplat/web/features/login/state/index.ts (90 bytes)
CREATE xplat/web/features/login/state/session.actions.ts (662 bytes)
CREATE xplat/web/features/login/state/session.effects.spec.ts (1017 bytes)
CREATE xplat/web/features/login/state/session.effects.ts (714 bytes)
CREATE xplat/web/features/login/state/session.reducer.spec.ts (401 bytes)
CREATE xplat/web/features/login/state/session.reducer.ts (474 bytes)
CREATE xplat/web/features/login/state/session.state.ts (219 bytes)
UPDATE xplat/nativescript/features/login/index.ts (88 bytes)
UPDATE xplat/nativescript/features/login/login.module.ts (755 bytes)
UPDATE xplat/web/features/login/index.ts (88 bytes)
UPDATE xplat/web/features/login/login.module.ts (755 bytes)
UPDATE package.json (4450 bytes)
```

As you can see it generated reducers, effects etc under `xplat/web/features/login` and `xplat/nativescript/features/login`.
I'd expect them to be generated under `libs/features/login`.

If I try without `--platforms` I get this error:
```bash
 > ng g ngrx session --feature login                             
libs/features/login/login.module.ts does not exist. Create the feature module first. For example: ng g feature login
```

But the file `libs/features/login/login.module.ts` is not created by `ng g feature login`.

### Expected
In most use-cases we want to share the effects and reducers between the platforms.
In rare cases we might want to have a platform specific store or more likely effects-class.

**Comment by NathanWalker** [comment]
@m-abs default behavior when `platforms` is specified is to create per specified platform (like how `component` and the other generators work).
Most of the time with ngrx (most common) as you mentioned is to share between platforms so `ng g ngrx session --feature login` would be the desired command in that case to generate in the lowest level to use everywhere (not confined to specified platforms but usable with any). 

I had contemplated whether `ngrx` should default to creating a module in libs when no platforms were specified and no module with same name were found. If it make sense to you for `ng g ngrx session --feature login` to create a login.module.ts configured for that state in libs then I'll add support for that - I like the sounds of that as it definitely would seem to me to be most common usage.

**Comment by m-abs** [comment]
Hi @NathanWalker 

> Would you think `ng g ngrx session` would create `session-state.module` in `libs/features/session`? 

You mean creating a new feature named `session` with the new store?
Yesterday I ended up doing something like that. I created a new feature named `session-data` and added a simple `session-data.module.ts`-file as expected by `ng g ngrx session --feature=session-data`.

> Further if you were to run `ng g ngrx session --feature=login` would you want just the state added as forFeature into the `libs/features/login/login.module`?

Yes, just that :)
Unfortunately that module-file isn't created by `ng g feature`.

**I'll try to list the various use-cases I can think of:**

1. New shared store without --platforms and --feature. `ng g ngrx name`
    * Creates a new feature under `lib/features/${name}` with a `${name}-data.module.ts` using `forFeature` and the `state`-folder etc.. 
    * Doesn't create anything under `xplat/`
2. New shared store with --feature. `ng g ngrx name --feature feature-name`
    * If the feature doesn't exist, creates it without the `xplat/`-part.
    * Adds the module-file if needed and adds `forFeature` to said module.
3. Platform specific store. `ng g ngrx name --platforms nativescript,web`
    * Similar to 1. but creates the files under `xplat/feature/{platform]/${name}/`
    * If the feature doesn't exist, create it. Generates the store under each platform.
3. Platform specific store. `ng g ngrx name --platform nativescript,web --feature feature-name`
    * If the feature doesn't exist, create it. Generates the store under each platform.
4. App specific store. `ng g ngrx name --projects web-base,nativescript-base`.
    * Adds the ngrx store under a specific app.

There might be more use-cases, but I couldn't think of more at the moment ;) 

**Another minor thing I noticed.**
Without xplat `ng g ngrx` puts the store in a `+state`-folder, xplat put them in a `state`-folder without the `+`.

**Comment by m-abs** [comment]
Hi @NathanWalker 

I'm having problems generating a new ngrx store.
I want to create a feature called `settings` and under that I want to create a state called `rendering-settings`.

```bash
> ng g ngrx rendering-settings --feature settings
libs/features/settings/settings.module.ts does not exist. Create the feature module first. For example: ng g feature settings
```

But `libs/features/settings/settings.module.ts` is not generated by: 
```bash
> ng g feature settings --platforms web,nativescript --only-module
CREATE xplat/web/features/settings/index.ts (34 bytes)
CREATE xplat/web/features/settings/settings.module.ts (171 bytes)
CREATE xplat/nativescript/features/settings/index.ts (35 bytes)
CREATE xplat/nativescript/features/settings/settings.module.ts (214 bytes)
UPDATE xplat/web/features/index.ts (166 bytes)
UPDATE xplat/nativescript/features/index.ts (193 bytes)
```

I've `@nstudio/schematics@6.2.6`

**Comment by m-abs** [comment]
This is no longer just a question.

Closing in favor of #34
