### ISSUE TITLE
Sample Feature errors ('loadChildren' of undefined)

### ISSUE THREAD

**Issue by wsmith-nwfsc** [nstudio/xplat#88]
I'm firing this up in a pretty pristine new nrwl nx workspace.
Various version info:
```
Angular CLI: 7.3.3
Node: 10.15.1
OS: win32 x64
Angular: 7.2.6
...
"@nrwl/nx": "7.6.2",
...
"@nstudio/schematics": "^7.3.2",
```
I ran through the sample feature setup (instructions on https://nstudio.io/xplat/ needs to be updated)  like so:
```
ng g xplat --prefix=foo --sample --platforms=web,electron
ng g app yourapp --sample
ng g app.electron electron-yourapp --sample --target=web-yourapp
```

Running the app yielded the following:
```
npm run start.web.yourapp
...
ERROR in Cannot read property 'loadChildren' of undefined
```
Something to do with routeBase() in `routes.ts`, but beyond that I don't know what the issue might be.
Thanks for working on this useful tool!

--
(Also, for electron, I ran into a Windows-specific `postinstall` minor stumbling block (found a closed bug on this #84) which looks like future version will fix. I manually removed the env variable portion from the script and it works (probably could also have just prefixed it with "set")
```
'ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES' is not recognized as an internal or external command
```

**Comment by NathanWalker** [comment]
@wsmith-nwfsc Thanks for reporting 👍 Will check this out soon. (in meantime let me know if you have issue without using the `--sample` flag)

**Comment by NathanWalker** [comment]
@wsmith-nwfsc I updated the instructions here (https://nstudio.io/xplat/) - the key thing was that when generating the web app:

**VERY IMPORTANT**: Choose `y` to the Routing question/prompt when generating the web app.

Made note of that in there now 👍

**Comment by NathanWalker** [comment]
@wsmith-nwfsc also you may be interested in this example which shows how to handle routing with electron considerations when live sync developing versus packaging for deploy:
https://github.com/nstudio/xplat-sample-electron-routing

**Comment by wsmith-nwfsc** [comment]
Excellent, thanks for your note,and xplat-sample-electron-routing answers a lot of questions.
