### ISSUE TITLE
Cannot update

### ISSUE THREAD

**Issue by julian-martinez-del-campo** [nstudio/xplat#9]
Running <code>ng update</code> produces the following error:

<code>
Not found : @test/scss
</code>

<hr>

Reproduction steps:
 * create-nx-workspace test
 * npm install @nstudio/schematics --save-dev
 * ng g xplat --prefix=foo --platforms=web,nativescript,ionic
 * ng update

**Comment by NathanWalker** [comment]
Hi @julian-martinez-del-campo  this is issue with angular cli and ng update actually:
angular/angular-cli#10614

The solution is to temporarily remove any file: ref dependencies in package, run ng update then add them back. Hopefully that will be fixed soon.

**Comment by julian-martinez-del-campo** [comment]
Thanks!

I had seen that problem reported but hadn't had any issues with any of my
other projects when running update, I guess those versions didn't have that
issue.

Cheers

**Comment by NathanWalker** [comment]
Thanks @julian-martinez-del-campo - please lemme know anything else you run into or that's confusing and we'll do our best to clear it up 👍
