### ISSUE TITLE
Nest application does not update the angular.json file

### ISSUE THREAD

**Issue by dungahk** [nstudio/xplat#94]
I have generated a nest application using app.nest but the angular.json file does not update.

Very good stuff you guys have! Thanks for the project, really enjoying it.

**Comment by NathanWalker** [comment]
Thanks @dungahk! since we aren’t using any angular build architect setups with nest we don’t modify for it however that may change in future. It should not affect your usage though I don’t believe?

**Comment by dungahk** [comment]
Hi @NathanWalker thanks for the response.

Because Nx adds a project to angular.json I was expecting xplat to do the same, I guess it doesn't hurt to have this as an option in the future like you mentioned, right?

I'm happy to try a PR.

Thanks again for the stuff you've done!
